// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Profiles.Infrastructure.Persistence;

#nullable disable

namespace Profiles.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240608020525_TableSubSkillC1")]
    partial class TableSubSkillC1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CityModel", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("cty_city_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("cty_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cty_name");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("prv_province_id");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("Name", "ProvinceId")
                        .IsUnique();

                    b.ToTable("city");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("fb5aa6d4-a820-47ae-8227-22bb5395579b"),
                            Disabled = false,
                            Name = "Leticia",
                            ProvinceId = new Guid("96dec272-ee22-4f19-bfd3-0c7c69564c56")
                        },
                        new
                        {
                            CityId = new Guid("0574c4fb-0d4f-4fbb-a162-de893cbd1213"),
                            Disabled = false,
                            Name = "Medellín",
                            ProvinceId = new Guid("4a71283b-539c-4a2c-a562-e380023f9784")
                        },
                        new
                        {
                            CityId = new Guid("3cdd4d66-ddc2-48eb-93f1-be6d2d9a5a0b"),
                            Disabled = false,
                            Name = "Apartadó",
                            ProvinceId = new Guid("4a71283b-539c-4a2c-a562-e380023f9784")
                        },
                        new
                        {
                            CityId = new Guid("62b58364-870c-4504-b56d-55f227a88483"),
                            Disabled = false,
                            Name = "Turbo",
                            ProvinceId = new Guid("4a71283b-539c-4a2c-a562-e380023f9784")
                        },
                        new
                        {
                            CityId = new Guid("c323a10b-3745-4308-b0dc-721793795c18"),
                            Disabled = false,
                            Name = "Arauca",
                            ProvinceId = new Guid("0dbcc619-0b05-48bb-a009-80cb937178d9")
                        },
                        new
                        {
                            CityId = new Guid("79a5ddbf-03f3-4d63-81a8-e62d3cf22ec7"),
                            Disabled = false,
                            Name = "Saravena",
                            ProvinceId = new Guid("0dbcc619-0b05-48bb-a009-80cb937178d9")
                        },
                        new
                        {
                            CityId = new Guid("8c018439-fa33-492c-8675-cff3137eb5c9"),
                            Disabled = false,
                            Name = "Fortul",
                            ProvinceId = new Guid("0dbcc619-0b05-48bb-a009-80cb937178d9")
                        },
                        new
                        {
                            CityId = new Guid("d8a52106-8685-444d-8dc8-ee8e5ceb2fe5"),
                            Disabled = false,
                            Name = "Barranquilla",
                            ProvinceId = new Guid("d8885b0a-e734-4818-85c8-938050365ed5")
                        },
                        new
                        {
                            CityId = new Guid("60bdccc3-6156-48f9-b20d-94b82e2f8407"),
                            Disabled = false,
                            Name = "Soledad",
                            ProvinceId = new Guid("d8885b0a-e734-4818-85c8-938050365ed5")
                        },
                        new
                        {
                            CityId = new Guid("5143af4e-7ffa-409b-bf6c-0db6ecbbcc29"),
                            Disabled = false,
                            Name = "Puerto Colombia",
                            ProvinceId = new Guid("d8885b0a-e734-4818-85c8-938050365ed5")
                        },
                        new
                        {
                            CityId = new Guid("b39d0ecd-12e4-486b-8531-06f2b689a0a8"),
                            Disabled = false,
                            Name = "Cartagena de Indias",
                            ProvinceId = new Guid("b7141ba9-096e-4e3c-ae5a-e6f86aad754d")
                        },
                        new
                        {
                            CityId = new Guid("a4942ac8-a15e-4f98-9211-0278d7895b3d"),
                            Disabled = false,
                            Name = "Magangué",
                            ProvinceId = new Guid("b7141ba9-096e-4e3c-ae5a-e6f86aad754d")
                        },
                        new
                        {
                            CityId = new Guid("8f084635-9420-4a2a-a427-c63fd9b20653"),
                            Disabled = false,
                            Name = "Cartagena del Chairá",
                            ProvinceId = new Guid("b7141ba9-096e-4e3c-ae5a-e6f86aad754d")
                        },
                        new
                        {
                            CityId = new Guid("cddc8edf-6e22-412d-914f-54ba280d463f"),
                            Disabled = false,
                            Name = "Tunja",
                            ProvinceId = new Guid("dff8df6d-bd35-4008-a6c5-be5637a3ff16")
                        },
                        new
                        {
                            CityId = new Guid("93399073-0dea-4186-aabe-fe8063bbd6e1"),
                            Disabled = false,
                            Name = "Sogamoso",
                            ProvinceId = new Guid("dff8df6d-bd35-4008-a6c5-be5637a3ff16")
                        },
                        new
                        {
                            CityId = new Guid("08248e24-55db-42c5-9682-3067505fd927"),
                            Disabled = false,
                            Name = "Duitama",
                            ProvinceId = new Guid("dff8df6d-bd35-4008-a6c5-be5637a3ff16")
                        },
                        new
                        {
                            CityId = new Guid("3497c9f6-f64c-4e33-9768-d753af9d1c21"),
                            Disabled = false,
                            Name = "Manizales",
                            ProvinceId = new Guid("f62c7508-e354-4581-acd3-94bbaa9cda47")
                        },
                        new
                        {
                            CityId = new Guid("03d807d3-8b28-43fc-acfd-25586936d065"),
                            Disabled = false,
                            Name = "Pereira",
                            ProvinceId = new Guid("f62c7508-e354-4581-acd3-94bbaa9cda47")
                        },
                        new
                        {
                            CityId = new Guid("5ada9cd8-3bf7-437d-afce-346df446ef10"),
                            Disabled = false,
                            Name = "Chinchiná",
                            ProvinceId = new Guid("f62c7508-e354-4581-acd3-94bbaa9cda47")
                        },
                        new
                        {
                            CityId = new Guid("bf1f2b63-d131-4882-a03b-c29b1b38c1b6"),
                            Disabled = false,
                            Name = "Florencia",
                            ProvinceId = new Guid("5c0bfc49-734f-4beb-ab6d-cb4686fb3087")
                        },
                        new
                        {
                            CityId = new Guid("16766f4d-b734-422f-913a-4bbb3625aac6"),
                            Disabled = false,
                            Name = "Cartagena del Chairá",
                            ProvinceId = new Guid("5c0bfc49-734f-4beb-ab6d-cb4686fb3087")
                        },
                        new
                        {
                            CityId = new Guid("16f9884c-3983-486a-a00d-dd441ede76aa"),
                            Disabled = false,
                            Name = "Morelia",
                            ProvinceId = new Guid("5c0bfc49-734f-4beb-ab6d-cb4686fb3087")
                        },
                        new
                        {
                            CityId = new Guid("c4e51087-719b-4870-b9f9-9c9e11bda3da"),
                            Disabled = false,
                            Name = "Yopal",
                            ProvinceId = new Guid("0802c59d-fab1-47ce-b0f8-8cfb8f8f22c0")
                        },
                        new
                        {
                            CityId = new Guid("7da946de-7cba-46ed-afc3-2503c8ddfac4"),
                            Disabled = false,
                            Name = "Aguazul",
                            ProvinceId = new Guid("0802c59d-fab1-47ce-b0f8-8cfb8f8f22c0")
                        },
                        new
                        {
                            CityId = new Guid("57a9d435-2148-48bc-9549-04e8d7959771"),
                            Disabled = false,
                            Name = "Tauramena",
                            ProvinceId = new Guid("0802c59d-fab1-47ce-b0f8-8cfb8f8f22c0")
                        },
                        new
                        {
                            CityId = new Guid("3f049c95-2978-4753-ad21-40b81cd4cc70"),
                            Disabled = false,
                            Name = "Popayán",
                            ProvinceId = new Guid("0ff58c2d-eb48-40e3-aa75-934f7a86d06b")
                        },
                        new
                        {
                            CityId = new Guid("610b86de-742b-403c-8fba-b4e68beb09a7"),
                            Disabled = false,
                            Name = "Silvia",
                            ProvinceId = new Guid("0ff58c2d-eb48-40e3-aa75-934f7a86d06b")
                        },
                        new
                        {
                            CityId = new Guid("9619bbef-ad62-4a23-b5f7-5b23c2534947"),
                            Disabled = false,
                            Name = "Santander de Quilichao",
                            ProvinceId = new Guid("0ff58c2d-eb48-40e3-aa75-934f7a86d06b")
                        },
                        new
                        {
                            CityId = new Guid("6e14cb7f-5afc-4aa0-93bf-a72e08c233ab"),
                            Disabled = false,
                            Name = "Valledupar",
                            ProvinceId = new Guid("3e42c273-ff0e-4a31-beac-e1818c10b3cf")
                        },
                        new
                        {
                            CityId = new Guid("40ba94c8-b5af-4e75-bb63-71905e4845cc"),
                            Disabled = false,
                            Name = "Aguachica",
                            ProvinceId = new Guid("3e42c273-ff0e-4a31-beac-e1818c10b3cf")
                        },
                        new
                        {
                            CityId = new Guid("1857a290-0fe6-4ac0-8f52-ede16113df81"),
                            Disabled = false,
                            Name = "La Paz",
                            ProvinceId = new Guid("3e42c273-ff0e-4a31-beac-e1818c10b3cf")
                        },
                        new
                        {
                            CityId = new Guid("32e30f6b-337a-4825-a437-38983dbc487b"),
                            Disabled = false,
                            Name = "Quibdó",
                            ProvinceId = new Guid("6c0c0a50-922c-4a23-b690-2cae82909ac8")
                        },
                        new
                        {
                            CityId = new Guid("df1fd82c-59c4-4900-ad93-3c4bcff61d2d"),
                            Disabled = false,
                            Name = "Istmina",
                            ProvinceId = new Guid("6c0c0a50-922c-4a23-b690-2cae82909ac8")
                        },
                        new
                        {
                            CityId = new Guid("e78c2cd0-7cc8-4f78-bd34-cf5c397de73c"),
                            Disabled = false,
                            Name = "Novita",
                            ProvinceId = new Guid("6c0c0a50-922c-4a23-b690-2cae82909ac8")
                        },
                        new
                        {
                            CityId = new Guid("ad0ed6cd-f99f-4caf-ac7d-1e42e937f097"),
                            Disabled = false,
                            Name = "Montería",
                            ProvinceId = new Guid("db18da0a-845e-44d0-aa4d-9029d5218ee9")
                        },
                        new
                        {
                            CityId = new Guid("f7827f92-482d-4378-b9a0-a2c70c24fe70"),
                            Disabled = false,
                            Name = "Cereté",
                            ProvinceId = new Guid("db18da0a-845e-44d0-aa4d-9029d5218ee9")
                        },
                        new
                        {
                            CityId = new Guid("f4ef265c-ec3a-43cc-98fd-db1b14e8a8c3"),
                            Disabled = false,
                            Name = "Lorica",
                            ProvinceId = new Guid("db18da0a-845e-44d0-aa4d-9029d5218ee9")
                        },
                        new
                        {
                            CityId = new Guid("5a4a5759-dd72-4af9-ac67-1c8c70b0b5ed"),
                            Disabled = false,
                            Name = "Bogotá",
                            ProvinceId = new Guid("3bafe12a-de84-4b7a-bbd4-ab981e9abf1c")
                        },
                        new
                        {
                            CityId = new Guid("5c41de35-cb8c-49bf-b4b7-79373d4aa2ec"),
                            Disabled = false,
                            Name = "Soacha",
                            ProvinceId = new Guid("3bafe12a-de84-4b7a-bbd4-ab981e9abf1c")
                        },
                        new
                        {
                            CityId = new Guid("982d7f67-713a-41ef-aee7-dc2eb7af7fd8"),
                            Disabled = false,
                            Name = "Zipaquirá",
                            ProvinceId = new Guid("3bafe12a-de84-4b7a-bbd4-ab981e9abf1c")
                        },
                        new
                        {
                            CityId = new Guid("95aa4b56-e6aa-4924-aaa0-729619ea626f"),
                            Disabled = false,
                            Name = "Inírida",
                            ProvinceId = new Guid("cc5eb796-358c-4a64-8dd0-4bc122e900eb")
                        },
                        new
                        {
                            CityId = new Guid("7e23c3fb-01e2-45da-80fd-541838a8d582"),
                            Disabled = false,
                            Name = "Puerto Inírida",
                            ProvinceId = new Guid("cc5eb796-358c-4a64-8dd0-4bc122e900eb")
                        },
                        new
                        {
                            CityId = new Guid("3ec7d984-2a65-4f8e-9938-1f9d9ea32d77"),
                            Disabled = false,
                            Name = "Memarí",
                            ProvinceId = new Guid("cc5eb796-358c-4a64-8dd0-4bc122e900eb")
                        },
                        new
                        {
                            CityId = new Guid("083af21c-b0f3-4bb4-9f04-a515bb8bb2ce"),
                            Disabled = false,
                            Name = "San José del Guaviare",
                            ProvinceId = new Guid("6eb495f7-ffe3-4346-8735-e98c95bf19bb")
                        },
                        new
                        {
                            CityId = new Guid("dc572ecc-2fc7-45c2-b96d-843f05bc6ebb"),
                            Disabled = false,
                            Name = "Calamar",
                            ProvinceId = new Guid("6eb495f7-ffe3-4346-8735-e98c95bf19bb")
                        },
                        new
                        {
                            CityId = new Guid("2d4d50cb-b317-484e-9377-7cb53fea3a59"),
                            Disabled = false,
                            Name = "El Retén",
                            ProvinceId = new Guid("6eb495f7-ffe3-4346-8735-e98c95bf19bb")
                        },
                        new
                        {
                            CityId = new Guid("7814c559-dcfb-4384-b893-a8873a218a2a"),
                            Disabled = false,
                            Name = "Neiva",
                            ProvinceId = new Guid("6ef1ee5d-822e-436f-96df-6095c696c7b0")
                        },
                        new
                        {
                            CityId = new Guid("fd52c2d4-37d9-4afe-9e26-ffa865839964"),
                            Disabled = false,
                            Name = "Garzón",
                            ProvinceId = new Guid("6ef1ee5d-822e-436f-96df-6095c696c7b0")
                        },
                        new
                        {
                            CityId = new Guid("098eaeb1-30bf-405e-a625-5c0130cf073c"),
                            Disabled = false,
                            Name = "Pitalito",
                            ProvinceId = new Guid("6ef1ee5d-822e-436f-96df-6095c696c7b0")
                        },
                        new
                        {
                            CityId = new Guid("58ba3a2a-e208-4736-a07c-4814d6d3f384"),
                            Disabled = false,
                            Name = "Riohacha",
                            ProvinceId = new Guid("f91cd7de-b9ea-45aa-98e0-f3e5a41c3c4c")
                        },
                        new
                        {
                            CityId = new Guid("47ab051a-5b69-4297-b7f8-44ffaff9b9a5"),
                            Disabled = false,
                            Name = "Maicao",
                            ProvinceId = new Guid("f91cd7de-b9ea-45aa-98e0-f3e5a41c3c4c")
                        },
                        new
                        {
                            CityId = new Guid("c98a94bf-87dd-42dd-b0ed-18e271b0ae21"),
                            Disabled = false,
                            Name = "Uribia",
                            ProvinceId = new Guid("f91cd7de-b9ea-45aa-98e0-f3e5a41c3c4c")
                        },
                        new
                        {
                            CityId = new Guid("7e783448-c30a-4e0b-95b0-8b1a616d75da"),
                            Disabled = false,
                            Name = "Santa Marta",
                            ProvinceId = new Guid("bafb1186-54ab-4474-99f7-3785a6fcdf92")
                        },
                        new
                        {
                            CityId = new Guid("c462e379-ab4d-415e-a515-d93d3bcc4ed0"),
                            Disabled = false,
                            Name = "Aracataca",
                            ProvinceId = new Guid("bafb1186-54ab-4474-99f7-3785a6fcdf92")
                        },
                        new
                        {
                            CityId = new Guid("987ca1b1-411a-49d8-99b3-042c37077631"),
                            Disabled = false,
                            Name = "Ciénaga",
                            ProvinceId = new Guid("bafb1186-54ab-4474-99f7-3785a6fcdf92")
                        },
                        new
                        {
                            CityId = new Guid("adc771e7-1053-4cca-9640-04d094928c7c"),
                            Disabled = false,
                            Name = "Villavicencio",
                            ProvinceId = new Guid("0558afd1-fb77-46fd-aabd-86f8f33f419e")
                        },
                        new
                        {
                            CityId = new Guid("99d4a4b3-7368-4944-b040-4dbc242766e4"),
                            Disabled = false,
                            Name = "Acacias",
                            ProvinceId = new Guid("0558afd1-fb77-46fd-aabd-86f8f33f419e")
                        },
                        new
                        {
                            CityId = new Guid("f0c40e66-76e7-4350-87bd-d0fb03bee9e0"),
                            Disabled = false,
                            Name = "Granada",
                            ProvinceId = new Guid("0558afd1-fb77-46fd-aabd-86f8f33f419e")
                        },
                        new
                        {
                            CityId = new Guid("01541e15-3076-4b9a-be74-55cf22958ba5"),
                            Disabled = false,
                            Name = "San Juan de Pasto",
                            ProvinceId = new Guid("782ae2d4-e56d-4d75-8d9b-90081841db53")
                        },
                        new
                        {
                            CityId = new Guid("c8a7d87d-78a6-422d-a34e-5c02918b9ac9"),
                            Disabled = false,
                            Name = "Tumaco",
                            ProvinceId = new Guid("782ae2d4-e56d-4d75-8d9b-90081841db53")
                        },
                        new
                        {
                            CityId = new Guid("4370cba8-17ed-4f1f-a30b-d5f622b01305"),
                            Disabled = false,
                            Name = "Ipiales",
                            ProvinceId = new Guid("782ae2d4-e56d-4d75-8d9b-90081841db53")
                        },
                        new
                        {
                            CityId = new Guid("035c827e-6285-477a-be84-10895281cee6"),
                            Disabled = false,
                            Name = "Cúcuta",
                            ProvinceId = new Guid("d13f4fcc-bbab-4798-9194-041547560ee8")
                        },
                        new
                        {
                            CityId = new Guid("309d8924-0e73-41c0-9ec7-772a3a6c34c3"),
                            Disabled = false,
                            Name = "Ocaña",
                            ProvinceId = new Guid("d13f4fcc-bbab-4798-9194-041547560ee8")
                        },
                        new
                        {
                            CityId = new Guid("8112b431-d141-4029-805b-2161b403f7d1"),
                            Disabled = false,
                            Name = "Pamplona",
                            ProvinceId = new Guid("d13f4fcc-bbab-4798-9194-041547560ee8")
                        },
                        new
                        {
                            CityId = new Guid("6ff95093-d2c0-4e2f-a53e-ae3d33928521"),
                            Disabled = false,
                            Name = "Mocoa",
                            ProvinceId = new Guid("e3a90731-04ec-4157-a535-8ed7f97b9b1d")
                        },
                        new
                        {
                            CityId = new Guid("108b4658-c712-4b87-8b1c-c6606c03dc02"),
                            Disabled = false,
                            Name = "Puerto Asís",
                            ProvinceId = new Guid("e3a90731-04ec-4157-a535-8ed7f97b9b1d")
                        },
                        new
                        {
                            CityId = new Guid("59cbed4b-9a19-4850-90cf-1296d128c3b0"),
                            Disabled = false,
                            Name = "Orito",
                            ProvinceId = new Guid("e3a90731-04ec-4157-a535-8ed7f97b9b1d")
                        },
                        new
                        {
                            CityId = new Guid("8db27c4f-8f1c-4d3f-bcad-a56bef5284ed"),
                            Disabled = false,
                            Name = "Armenia",
                            ProvinceId = new Guid("f3a8a3cf-4791-42f1-a1b8-1b9f0fc7bdd0")
                        },
                        new
                        {
                            CityId = new Guid("40852fa3-3df2-45ee-ac21-f43c662ffdd3"),
                            Disabled = false,
                            Name = "Calarcá",
                            ProvinceId = new Guid("f3a8a3cf-4791-42f1-a1b8-1b9f0fc7bdd0")
                        },
                        new
                        {
                            CityId = new Guid("5ee3426f-b6ba-4ec2-bac5-5b91d231ec00"),
                            Disabled = false,
                            Name = "La Tebaida",
                            ProvinceId = new Guid("f3a8a3cf-4791-42f1-a1b8-1b9f0fc7bdd0")
                        },
                        new
                        {
                            CityId = new Guid("e0279d2f-6985-4ca4-bc8d-0b9a6a38b24e"),
                            Disabled = false,
                            Name = "Pereira",
                            ProvinceId = new Guid("53e107a0-162b-42c6-a19f-45fe8a54c06e")
                        },
                        new
                        {
                            CityId = new Guid("712a0acb-307f-4c47-bf61-49dfaf072a81"),
                            Disabled = false,
                            Name = "Dosquebradas",
                            ProvinceId = new Guid("53e107a0-162b-42c6-a19f-45fe8a54c06e")
                        },
                        new
                        {
                            CityId = new Guid("5ba5b4c9-108e-44a2-bd84-7576de4fb58b"),
                            Disabled = false,
                            Name = "Santa Rosa de Cabal",
                            ProvinceId = new Guid("53e107a0-162b-42c6-a19f-45fe8a54c06e")
                        },
                        new
                        {
                            CityId = new Guid("c63004ed-0e90-449a-8163-814cc6543a7f"),
                            Disabled = false,
                            Name = "San Andrés",
                            ProvinceId = new Guid("0ac25ad7-d9d9-4fa2-b6b8-af4c8e6d9f82")
                        },
                        new
                        {
                            CityId = new Guid("8fe2e518-d6c3-457a-89be-b26de3030e1b"),
                            Disabled = false,
                            Name = "Providencia",
                            ProvinceId = new Guid("0ac25ad7-d9d9-4fa2-b6b8-af4c8e6d9f82")
                        },
                        new
                        {
                            CityId = new Guid("3845ed06-c01c-41df-ba69-b3c5655af974"),
                            Disabled = false,
                            Name = "Santa Catalina",
                            ProvinceId = new Guid("0ac25ad7-d9d9-4fa2-b6b8-af4c8e6d9f82")
                        },
                        new
                        {
                            CityId = new Guid("ebb4a753-ef7c-4ec4-a7ff-bd306b238988"),
                            Disabled = false,
                            Name = "Bucaramanga",
                            ProvinceId = new Guid("759ce442-96a2-40f7-9107-ccdbb0d01e80")
                        },
                        new
                        {
                            CityId = new Guid("2a9f14ee-1b0f-4e30-b097-b26710963698"),
                            Disabled = false,
                            Name = "Barrancabermeja",
                            ProvinceId = new Guid("759ce442-96a2-40f7-9107-ccdbb0d01e80")
                        },
                        new
                        {
                            CityId = new Guid("3588fce5-c17d-4d42-9127-5cb04642d09b"),
                            Disabled = false,
                            Name = "Piedecuesta",
                            ProvinceId = new Guid("759ce442-96a2-40f7-9107-ccdbb0d01e80")
                        },
                        new
                        {
                            CityId = new Guid("3c61d985-371d-4e2b-bf90-b5a35f7a836a"),
                            Disabled = false,
                            Name = "Sincelejo",
                            ProvinceId = new Guid("c01a41e5-5ba9-4aa0-bf20-75ed64af1370")
                        },
                        new
                        {
                            CityId = new Guid("49f8ab8b-1a4a-4c61-9eff-2e8cfa0bef8b"),
                            Disabled = false,
                            Name = "Corozal",
                            ProvinceId = new Guid("c01a41e5-5ba9-4aa0-bf20-75ed64af1370")
                        },
                        new
                        {
                            CityId = new Guid("8ff84bf8-31af-4081-b46f-2ac733037643"),
                            Disabled = false,
                            Name = "Montería",
                            ProvinceId = new Guid("c01a41e5-5ba9-4aa0-bf20-75ed64af1370")
                        },
                        new
                        {
                            CityId = new Guid("bda74e57-345c-4c01-bbec-b80f4647ed72"),
                            Disabled = false,
                            Name = "Ibagué",
                            ProvinceId = new Guid("e8a20b7c-ab57-408f-97a1-9d5dd851795c")
                        },
                        new
                        {
                            CityId = new Guid("08186db9-b3b8-40c1-9e46-516ef47a90e6"),
                            Disabled = false,
                            Name = "Honda",
                            ProvinceId = new Guid("e8a20b7c-ab57-408f-97a1-9d5dd851795c")
                        },
                        new
                        {
                            CityId = new Guid("dea8bed2-4bea-4372-ba41-11d233f83c0c"),
                            Disabled = false,
                            Name = "Armero Guayabal",
                            ProvinceId = new Guid("e8a20b7c-ab57-408f-97a1-9d5dd851795c")
                        },
                        new
                        {
                            CityId = new Guid("7c1197ff-9b94-4f88-b54a-884c9bfab45e"),
                            Disabled = false,
                            Name = "Cali",
                            ProvinceId = new Guid("488a8b88-41fd-4031-aabc-b1558fbb8095")
                        },
                        new
                        {
                            CityId = new Guid("c829edeb-79a5-4349-9de4-85ea6e40c813"),
                            Disabled = false,
                            Name = "Palmira",
                            ProvinceId = new Guid("488a8b88-41fd-4031-aabc-b1558fbb8095")
                        },
                        new
                        {
                            CityId = new Guid("67568adb-d0b1-4c1b-8f91-a204bd3a0bfc"),
                            Disabled = false,
                            Name = "Buenaventura",
                            ProvinceId = new Guid("488a8b88-41fd-4031-aabc-b1558fbb8095")
                        },
                        new
                        {
                            CityId = new Guid("19906ef1-aea7-4e4b-a56c-b34a3a0a37b6"),
                            Disabled = false,
                            Name = "Mitú",
                            ProvinceId = new Guid("51db2038-7d2b-4987-9555-78485179df10")
                        },
                        new
                        {
                            CityId = new Guid("b8a53129-0386-41f3-8b38-445e74e97aee"),
                            Disabled = false,
                            Name = "Yavaraté",
                            ProvinceId = new Guid("51db2038-7d2b-4987-9555-78485179df10")
                        },
                        new
                        {
                            CityId = new Guid("583190ea-cdcd-4cea-a1ea-3e0cbeacd028"),
                            Disabled = false,
                            Name = "Santa Rosalía",
                            ProvinceId = new Guid("51db2038-7d2b-4987-9555-78485179df10")
                        },
                        new
                        {
                            CityId = new Guid("e094e307-97f7-4204-8437-ac189efa0089"),
                            Disabled = false,
                            Name = "Puerto Carreño",
                            ProvinceId = new Guid("72a91982-f9bf-488d-ac68-bfc071778fa8")
                        },
                        new
                        {
                            CityId = new Guid("df00a67f-177b-452e-9826-4f891faa5388"),
                            Disabled = false,
                            Name = "La Primavera",
                            ProvinceId = new Guid("72a91982-f9bf-488d-ac68-bfc071778fa8")
                        },
                        new
                        {
                            CityId = new Guid("1cb73119-1b74-4d45-b158-2984d2cd6e4a"),
                            Disabled = false,
                            Name = "Santa Helena",
                            ProvinceId = new Guid("72a91982-f9bf-488d-ac68-bfc071778fa8")
                        },
                        new
                        {
                            CityId = new Guid("831313a1-bcff-4ff6-9cf1-b0f0f155d3ee"),
                            Disabled = false,
                            Name = "Cuenca",
                            ProvinceId = new Guid("24b9652e-eefa-42ad-bbeb-3081bfd44f78")
                        },
                        new
                        {
                            CityId = new Guid("fc40f84d-bc5d-47b2-9c73-cf0972e612f4"),
                            Disabled = false,
                            Name = "Girón",
                            ProvinceId = new Guid("24b9652e-eefa-42ad-bbeb-3081bfd44f78")
                        },
                        new
                        {
                            CityId = new Guid("48bb9d2b-7757-4302-beea-40cc1d5b8e77"),
                            Disabled = false,
                            Name = "Guaranda",
                            ProvinceId = new Guid("5a422b70-a5c0-46c2-bc1c-78bdbba67747")
                        },
                        new
                        {
                            CityId = new Guid("2987c4b8-2283-4339-a2f5-d9287ba6953d"),
                            Disabled = false,
                            Name = "San Miguel de Bolívar",
                            ProvinceId = new Guid("5a422b70-a5c0-46c2-bc1c-78bdbba67747")
                        },
                        new
                        {
                            CityId = new Guid("1cd46991-bede-49e1-8435-c222a51c8b27"),
                            Disabled = false,
                            Name = "Azogues",
                            ProvinceId = new Guid("971e9a4f-2fb5-49a9-ad99-061f02f51b4b")
                        },
                        new
                        {
                            CityId = new Guid("a92b11c0-07ee-4c71-a827-d5fd35e81d0a"),
                            Disabled = false,
                            Name = "El Tambo",
                            ProvinceId = new Guid("971e9a4f-2fb5-49a9-ad99-061f02f51b4b")
                        },
                        new
                        {
                            CityId = new Guid("225e709d-080a-4aa8-b4ed-291d4d7f1d7a"),
                            Disabled = false,
                            Name = "Tulcán",
                            ProvinceId = new Guid("308f1aad-e07b-442a-8e3a-0438c0eda523")
                        },
                        new
                        {
                            CityId = new Guid("85ab5f4d-0fb1-4d0c-9ea5-7fd7560675c8"),
                            Disabled = false,
                            Name = "El Guabo",
                            ProvinceId = new Guid("308f1aad-e07b-442a-8e3a-0438c0eda523")
                        },
                        new
                        {
                            CityId = new Guid("269084d1-2301-4e54-8656-189928759e2a"),
                            Disabled = false,
                            Name = "Riobamba",
                            ProvinceId = new Guid("33d57d03-67db-4eda-a6c2-2f7002d99e08")
                        },
                        new
                        {
                            CityId = new Guid("5a6317dc-10f7-4282-b709-2615f2d2764a"),
                            Disabled = false,
                            Name = "Alausí",
                            ProvinceId = new Guid("33d57d03-67db-4eda-a6c2-2f7002d99e08")
                        },
                        new
                        {
                            CityId = new Guid("d8e0899e-002d-4572-8807-b1c7fcff4ad4"),
                            Disabled = false,
                            Name = "Latacunga",
                            ProvinceId = new Guid("6ac34348-0493-42c5-ab3f-1060e9b8b139")
                        },
                        new
                        {
                            CityId = new Guid("b8f0498f-5de2-40c4-8d99-0e5ea7c542d8"),
                            Disabled = false,
                            Name = "Salcedo",
                            ProvinceId = new Guid("6ac34348-0493-42c5-ab3f-1060e9b8b139")
                        },
                        new
                        {
                            CityId = new Guid("cd3734c6-237e-473f-8751-d9d64aeb5250"),
                            Disabled = false,
                            Name = "Machala",
                            ProvinceId = new Guid("a8a6ad0f-2d98-41fc-9641-58b8711b31d7")
                        },
                        new
                        {
                            CityId = new Guid("d27655d4-ec2e-4fcc-b888-22cdc5683446"),
                            Disabled = false,
                            Name = "Santa Rosa",
                            ProvinceId = new Guid("a8a6ad0f-2d98-41fc-9641-58b8711b31d7")
                        },
                        new
                        {
                            CityId = new Guid("3b3fc3fd-1c3d-41da-b781-295fe9415728"),
                            Disabled = false,
                            Name = "Esmeraldas",
                            ProvinceId = new Guid("728028b8-56f5-4cb8-b95c-0cae27d8b966")
                        },
                        new
                        {
                            CityId = new Guid("46cb80e8-5fe5-48df-8fe9-a5ff3313d715"),
                            Disabled = false,
                            Name = "Atacames",
                            ProvinceId = new Guid("728028b8-56f5-4cb8-b95c-0cae27d8b966")
                        },
                        new
                        {
                            CityId = new Guid("c4f05d37-a761-49bd-8143-1efdbc7efb25"),
                            Disabled = false,
                            Name = "Puerto Baquerizo Moreno",
                            ProvinceId = new Guid("7949720f-d2d7-4085-8ef7-55cae9a75d2e")
                        },
                        new
                        {
                            CityId = new Guid("b3da86f0-2fd9-420b-9772-0de8768a8be8"),
                            Disabled = false,
                            Name = "San Cristóbal",
                            ProvinceId = new Guid("7949720f-d2d7-4085-8ef7-55cae9a75d2e")
                        },
                        new
                        {
                            CityId = new Guid("d2579b3e-94c6-4d42-afcc-4d4e61050f04"),
                            Disabled = false,
                            Name = "Guayaquil",
                            ProvinceId = new Guid("fc144541-84d2-44be-a1be-d3b46e69326f")
                        },
                        new
                        {
                            CityId = new Guid("6530f1de-e97a-4791-9483-f23319a57e85"),
                            Disabled = false,
                            Name = "Durán",
                            ProvinceId = new Guid("fc144541-84d2-44be-a1be-d3b46e69326f")
                        },
                        new
                        {
                            CityId = new Guid("dfe785bc-de0c-462f-9023-83078a1bfaf4"),
                            Disabled = false,
                            Name = "Ibarra",
                            ProvinceId = new Guid("cfa298f4-49c2-4699-9a0c-e00bde786c28")
                        },
                        new
                        {
                            CityId = new Guid("114b698e-31f6-4245-b2c7-299e3c344f5a"),
                            Disabled = false,
                            Name = "Otavalo",
                            ProvinceId = new Guid("cfa298f4-49c2-4699-9a0c-e00bde786c28")
                        },
                        new
                        {
                            CityId = new Guid("deafce49-f1a4-4243-917d-464970b8833f"),
                            Disabled = false,
                            Name = "Loja",
                            ProvinceId = new Guid("fd5f79f3-8e4c-4e64-974f-0e6c39caf477")
                        },
                        new
                        {
                            CityId = new Guid("a234b8a0-ccb0-4f3b-bf41-b49c62b46e6c"),
                            Disabled = false,
                            Name = "Saraguro",
                            ProvinceId = new Guid("fd5f79f3-8e4c-4e64-974f-0e6c39caf477")
                        },
                        new
                        {
                            CityId = new Guid("a500f9b7-6e03-4454-b454-e19336507d0c"),
                            Disabled = false,
                            Name = "Portoviejo",
                            ProvinceId = new Guid("dd0db58a-99c7-41f3-a53e-13ddc526beea")
                        },
                        new
                        {
                            CityId = new Guid("5d1420ca-6197-4827-a5cf-21bbad951bc2"),
                            Disabled = false,
                            Name = "Manta",
                            ProvinceId = new Guid("dd0db58a-99c7-41f3-a53e-13ddc526beea")
                        },
                        new
                        {
                            CityId = new Guid("8a58b0c7-75e0-4cb2-86ce-b53690f976a6"),
                            Disabled = false,
                            Name = "Chone",
                            ProvinceId = new Guid("dd0db58a-99c7-41f3-a53e-13ddc526beea")
                        },
                        new
                        {
                            CityId = new Guid("5771bca8-3781-4cd8-9e97-4aa32d63599c"),
                            Disabled = false,
                            Name = "Macas",
                            ProvinceId = new Guid("676005c8-9187-404d-9ee4-d8f882c5f6fb")
                        },
                        new
                        {
                            CityId = new Guid("81dce995-fe7c-4dd4-8c7b-9184a0c1c611"),
                            Disabled = false,
                            Name = "Gualaquiza",
                            ProvinceId = new Guid("676005c8-9187-404d-9ee4-d8f882c5f6fb")
                        },
                        new
                        {
                            CityId = new Guid("c14742bc-7543-4ad6-8e1c-0d1eeddad76c"),
                            Disabled = false,
                            Name = "Tena",
                            ProvinceId = new Guid("4debb243-f290-4703-b61b-243893562aa9")
                        },
                        new
                        {
                            CityId = new Guid("600d0ba6-64a3-4a54-bb2e-4519d03fd43f"),
                            Disabled = false,
                            Name = "Archidona",
                            ProvinceId = new Guid("4debb243-f290-4703-b61b-243893562aa9")
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CountryModel", b =>
                {
                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ctr_country_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("ctr_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctr_name");

                    b.HasKey("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("country");

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Colombia"
                        },
                        new
                        {
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Ecuador"
                        },
                        new
                        {
                            CountryId = new Guid("5e1a3ed3-c4df-4ee0-b9ee-ea8b6c3aa23a"),
                            Disabled = false,
                            Name = "Venezuela"
                        },
                        new
                        {
                            CountryId = new Guid("aaae3f0b-5c07-4aed-9a62-0de77cc975b5"),
                            Disabled = false,
                            Name = "Panamá"
                        },
                        new
                        {
                            CountryId = new Guid("ed0a15a7-6b9e-4642-8ace-99fb95d0fce0"),
                            Disabled = false,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            CountryId = new Guid("c8bfc3d2-34f5-4591-bb90-c4e3f5d5aa7e"),
                            Disabled = false,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            CountryId = new Guid("152273a1-820f-4de6-af39-dede1498012f"),
                            Disabled = false,
                            Name = "Honduras"
                        },
                        new
                        {
                            CountryId = new Guid("3e9d3e7d-8b25-4f4a-9178-2e7f47fdf786"),
                            Disabled = false,
                            Name = "Guatemala"
                        },
                        new
                        {
                            CountryId = new Guid("d910da69-5dd5-4d0d-ae85-b6e8540b1b27"),
                            Disabled = false,
                            Name = "El Salvador"
                        },
                        new
                        {
                            CountryId = new Guid("fd0754a2-eb5f-49c0-bd92-454d2c844786"),
                            Disabled = false,
                            Name = "Belize"
                        },
                        new
                        {
                            CountryId = new Guid("0b769380-c6c8-4406-b814-c69a3af0c4f3"),
                            Disabled = false,
                            Name = "México"
                        },
                        new
                        {
                            CountryId = new Guid("2580a49e-5f8e-4258-ac44-ac93e0fb0bcc"),
                            Disabled = false,
                            Name = "Perú"
                        },
                        new
                        {
                            CountryId = new Guid("0f81b1b1-dae2-4ec6-9e8a-82e58681f833"),
                            Disabled = false,
                            Name = "Chile"
                        },
                        new
                        {
                            CountryId = new Guid("46a8c546-3275-48c1-aa10-34f02b803dc0"),
                            Disabled = false,
                            Name = "Argentina"
                        },
                        new
                        {
                            CountryId = new Guid("742cd17b-6a93-4f17-9231-c500aaa56912"),
                            Disabled = false,
                            Name = "Brasil"
                        },
                        new
                        {
                            CountryId = new Guid("4fbc8640-e7db-4287-bb29-36f2e13f045e"),
                            Disabled = false,
                            Name = "Paraguay"
                        },
                        new
                        {
                            CountryId = new Guid("480676f2-d19c-42a5-a517-13ed65fd67e9"),
                            Disabled = false,
                            Name = "Uruguay"
                        },
                        new
                        {
                            CountryId = new Guid("73c41155-5e86-438f-b76b-9462ed60008f"),
                            Disabled = false,
                            Name = "Bolivia"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.LevelModel", b =>
                {
                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_level_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rol_description");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("rol_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("LevelId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("level");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProfessionalModel", b =>
                {
                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("prf_professional_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("prf_disabled");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prf_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prf_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProfessionalId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("professional");

                    b.HasData(
                        new
                        {
                            ProfessionalId = new Guid("d5497875-54cc-4856-872a-a7c368b206c5"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5969),
                            Disabled = false,
                            Email = "juanperez@gmail.com",
                            Name = "Juan Pérez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("7b44f984-c556-49d9-8f47-c103d3fa5b3a"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5976),
                            Disabled = false,
                            Email = "mariagarcia@gmail.com",
                            Name = "María García"
                        },
                        new
                        {
                            ProfessionalId = new Guid("35d07347-c58f-4304-b43b-f54dc77c058c"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5980),
                            Disabled = false,
                            Email = "pedrolopez@gmail.com",
                            Name = "Pedro López"
                        },
                        new
                        {
                            ProfessionalId = new Guid("bec38ea6-0275-4ad3-9c01-679865a3abaa"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5984),
                            Disabled = false,
                            Email = "anasanchez@gmail.com",
                            Name = "Ana Sánchez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("6f6e3034-b13f-481b-ac65-0178437801b1"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5988),
                            Disabled = false,
                            Email = "carlosrodriguez@gmail.com",
                            Name = "Carlos Rodríguez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("2d448f0d-7c0e-4941-8d10-7f620dbd8a69"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5993),
                            Disabled = false,
                            Email = "isabelmartinez@gmail.com",
                            Name = "Isabel Martínez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("60ac007b-9778-4943-aab3-8619044ae702"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5997),
                            Disabled = false,
                            Email = "diegogomez@gmail.com",
                            Name = "Diego Gómez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("d5d37eca-0229-492b-ae26-24cdc47c3200"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(6001),
                            Disabled = false,
                            Email = "sandramoreno@gmail.com",
                            Name = "Sandra Moreno"
                        },
                        new
                        {
                            ProfessionalId = new Guid("57b6fbce-982a-4bae-8d36-2f7e69232bd2"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(6004),
                            Disabled = false,
                            Email = "andresfernandez@gmail.com",
                            Name = "Andrés Fernández"
                        },
                        new
                        {
                            ProfessionalId = new Guid("1c1a95bb-0e45-4a5f-ac7c-0a2775e8b964"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(6009),
                            Disabled = false,
                            Email = "lauragonzalez@gmail.com",
                            Name = "Laura González"
                        },
                        new
                        {
                            ProfessionalId = new Guid("8838f043-ad58-463e-8a64-de72171abb89"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(6013),
                            Disabled = false,
                            Email = "javiermunoz@gmail.com",
                            Name = "Javier Muñoz"
                        },
                        new
                        {
                            ProfessionalId = new Guid("af51ce95-6152-4f58-97e1-7120d7d8f22c"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(6016),
                            Disabled = false,
                            Email = "patriciablanco@gmail.com",
                            Name = "Patricia Blanco"
                        },
                        new
                        {
                            ProfessionalId = new Guid("9b0c3c12-3705-41e6-8217-eaf54ee5ca83"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(6020),
                            Disabled = false,
                            Email = "josegutierrez@gmail.com",
                            Name = "José Gutiérrez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("650aab49-4e20-4b20-b7ad-bc66538851a8"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(6024),
                            Disabled = false,
                            Email = "aliciaruis@gmail.com",
                            Name = "Alicia Ruiz"
                        },
                        new
                        {
                            ProfessionalId = new Guid("762a4417-cea4-4f44-9b3c-7fcd73ead852"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(6028),
                            Disabled = false,
                            Email = "luisvazquez@gmail.com",
                            Name = "Luis Vázquez"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("prv_province_id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ctr_country_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("prv_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prv_name");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name", "CountryId")
                        .IsUnique();

                    b.ToTable("province");

                    b.HasData(
                        new
                        {
                            ProvinceId = new Guid("96dec272-ee22-4f19-bfd3-0c7c69564c56"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Amazonas"
                        },
                        new
                        {
                            ProvinceId = new Guid("4a71283b-539c-4a2c-a562-e380023f9784"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Antioquia"
                        },
                        new
                        {
                            ProvinceId = new Guid("0dbcc619-0b05-48bb-a009-80cb937178d9"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Arauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("d8885b0a-e734-4818-85c8-938050365ed5"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Atlántico"
                        },
                        new
                        {
                            ProvinceId = new Guid("b7141ba9-096e-4e3c-ae5a-e6f86aad754d"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Bolívar"
                        },
                        new
                        {
                            ProvinceId = new Guid("dff8df6d-bd35-4008-a6c5-be5637a3ff16"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Boyacá"
                        },
                        new
                        {
                            ProvinceId = new Guid("f62c7508-e354-4581-acd3-94bbaa9cda47"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Caldas"
                        },
                        new
                        {
                            ProvinceId = new Guid("5c0bfc49-734f-4beb-ab6d-cb4686fb3087"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Caquetá"
                        },
                        new
                        {
                            ProvinceId = new Guid("0802c59d-fab1-47ce-b0f8-8cfb8f8f22c0"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Casanare"
                        },
                        new
                        {
                            ProvinceId = new Guid("0ff58c2d-eb48-40e3-aa75-934f7a86d06b"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Cauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("3e42c273-ff0e-4a31-beac-e1818c10b3cf"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Cesar"
                        },
                        new
                        {
                            ProvinceId = new Guid("6c0c0a50-922c-4a23-b690-2cae82909ac8"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Chocó"
                        },
                        new
                        {
                            ProvinceId = new Guid("db18da0a-845e-44d0-aa4d-9029d5218ee9"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Córdoba"
                        },
                        new
                        {
                            ProvinceId = new Guid("3bafe12a-de84-4b7a-bbd4-ab981e9abf1c"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Cundinamarca"
                        },
                        new
                        {
                            ProvinceId = new Guid("cc5eb796-358c-4a64-8dd0-4bc122e900eb"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Guainía"
                        },
                        new
                        {
                            ProvinceId = new Guid("6eb495f7-ffe3-4346-8735-e98c95bf19bb"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Guaviare"
                        },
                        new
                        {
                            ProvinceId = new Guid("6ef1ee5d-822e-436f-96df-6095c696c7b0"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Huila"
                        },
                        new
                        {
                            ProvinceId = new Guid("f91cd7de-b9ea-45aa-98e0-f3e5a41c3c4c"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "La Guajira"
                        },
                        new
                        {
                            ProvinceId = new Guid("bafb1186-54ab-4474-99f7-3785a6fcdf92"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Magdalena"
                        },
                        new
                        {
                            ProvinceId = new Guid("0558afd1-fb77-46fd-aabd-86f8f33f419e"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Meta"
                        },
                        new
                        {
                            ProvinceId = new Guid("782ae2d4-e56d-4d75-8d9b-90081841db53"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Nariño"
                        },
                        new
                        {
                            ProvinceId = new Guid("d13f4fcc-bbab-4798-9194-041547560ee8"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Norte de Santander"
                        },
                        new
                        {
                            ProvinceId = new Guid("e3a90731-04ec-4157-a535-8ed7f97b9b1d"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Putumayo"
                        },
                        new
                        {
                            ProvinceId = new Guid("f3a8a3cf-4791-42f1-a1b8-1b9f0fc7bdd0"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Quindío"
                        },
                        new
                        {
                            ProvinceId = new Guid("53e107a0-162b-42c6-a19f-45fe8a54c06e"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Risaralda"
                        },
                        new
                        {
                            ProvinceId = new Guid("0ac25ad7-d9d9-4fa2-b6b8-af4c8e6d9f82"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "San Andrés y Providencia"
                        },
                        new
                        {
                            ProvinceId = new Guid("759ce442-96a2-40f7-9107-ccdbb0d01e80"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Santander"
                        },
                        new
                        {
                            ProvinceId = new Guid("c01a41e5-5ba9-4aa0-bf20-75ed64af1370"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Sucre"
                        },
                        new
                        {
                            ProvinceId = new Guid("e8a20b7c-ab57-408f-97a1-9d5dd851795c"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Tolima"
                        },
                        new
                        {
                            ProvinceId = new Guid("488a8b88-41fd-4031-aabc-b1558fbb8095"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Valle del Cauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("51db2038-7d2b-4987-9555-78485179df10"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Vaupés"
                        },
                        new
                        {
                            ProvinceId = new Guid("72a91982-f9bf-488d-ac68-bfc071778fa8"),
                            CountryId = new Guid("8fa2aead-bb59-4949-bc9d-529c188453a2"),
                            Disabled = false,
                            Name = "Vichada"
                        },
                        new
                        {
                            ProvinceId = new Guid("24b9652e-eefa-42ad-bbeb-3081bfd44f78"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Azuay"
                        },
                        new
                        {
                            ProvinceId = new Guid("5a422b70-a5c0-46c2-bc1c-78bdbba67747"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Bolívar"
                        },
                        new
                        {
                            ProvinceId = new Guid("971e9a4f-2fb5-49a9-ad99-061f02f51b4b"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Cañar"
                        },
                        new
                        {
                            ProvinceId = new Guid("308f1aad-e07b-442a-8e3a-0438c0eda523"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Carchi"
                        },
                        new
                        {
                            ProvinceId = new Guid("33d57d03-67db-4eda-a6c2-2f7002d99e08"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Chimborazo"
                        },
                        new
                        {
                            ProvinceId = new Guid("6ac34348-0493-42c5-ab3f-1060e9b8b139"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Cotopaxi"
                        },
                        new
                        {
                            ProvinceId = new Guid("a8a6ad0f-2d98-41fc-9641-58b8711b31d7"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "El Oro"
                        },
                        new
                        {
                            ProvinceId = new Guid("728028b8-56f5-4cb8-b95c-0cae27d8b966"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Esmeraldas"
                        },
                        new
                        {
                            ProvinceId = new Guid("7949720f-d2d7-4085-8ef7-55cae9a75d2e"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Galápagos"
                        },
                        new
                        {
                            ProvinceId = new Guid("fc144541-84d2-44be-a1be-d3b46e69326f"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Guayas"
                        },
                        new
                        {
                            ProvinceId = new Guid("cfa298f4-49c2-4699-9a0c-e00bde786c28"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Imbabura"
                        },
                        new
                        {
                            ProvinceId = new Guid("fd5f79f3-8e4c-4e64-974f-0e6c39caf477"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Loja"
                        },
                        new
                        {
                            ProvinceId = new Guid("dd0db58a-99c7-41f3-a53e-13ddc526beea"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Manabí"
                        },
                        new
                        {
                            ProvinceId = new Guid("676005c8-9187-404d-9ee4-d8f882c5f6fb"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Morona Santiago"
                        },
                        new
                        {
                            ProvinceId = new Guid("4debb243-f290-4703-b61b-243893562aa9"),
                            CountryId = new Guid("cd8b79cb-8931-45f2-b4a7-ef442544319e"),
                            Disabled = false,
                            Name = "Napo"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.RoleModel", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_role_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rol_description");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("rol_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("role");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("1429be8f-23f3-4d90-afda-ba8dc7557213"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5801),
                            Disabled = false,
                            Name = "Developer"
                        },
                        new
                        {
                            RoleId = new Guid("fa8af4ba-eabc-423a-88a4-ef196eef8d53"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5807),
                            Disabled = false,
                            Name = "Designer"
                        },
                        new
                        {
                            RoleId = new Guid("48247419-8e95-413b-81e3-61393ce5f1bf"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5811),
                            Disabled = false,
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = new Guid("cce4c296-4f4a-4a36-8845-881ef830e7ea"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5815),
                            Disabled = false,
                            Name = "QA"
                        },
                        new
                        {
                            RoleId = new Guid("868b2635-4b67-45c6-9027-7f3960d3ce1f"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5819),
                            Disabled = false,
                            Name = "DevOps"
                        },
                        new
                        {
                            RoleId = new Guid("b35e67e9-4683-4c68-8688-d0b7a851e1cb"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5823),
                            Disabled = false,
                            Name = "Data Scientist"
                        },
                        new
                        {
                            RoleId = new Guid("727a8d9c-fbf7-42c9-998a-4723f38940b9"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5827),
                            Disabled = false,
                            Name = "UX/UI Designer"
                        },
                        new
                        {
                            RoleId = new Guid("fec0c7d9-014c-41ce-8f0f-56352c63c790"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5831),
                            Disabled = false,
                            Name = "Product Owner"
                        },
                        new
                        {
                            RoleId = new Guid("4f2f7855-6f4c-4a5b-9829-eb1c5d9c49cb"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5835),
                            Disabled = false,
                            Name = "Scrum Master"
                        },
                        new
                        {
                            RoleId = new Guid("c938fa81-dc49-42df-8a9f-a2b9c54accaa"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5839),
                            Disabled = false,
                            Name = "Architect"
                        },
                        new
                        {
                            RoleId = new Guid("2440043b-3435-4b0f-b269-4860029a26cf"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5843),
                            Disabled = false,
                            Name = "Lead Developer"
                        },
                        new
                        {
                            RoleId = new Guid("14fc9af6-74d2-41e8-a8d6-f904f4664888"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5846),
                            Disabled = false,
                            Name = "Lead Designer"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.SkillModel", b =>
                {
                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skl_skill_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("skl_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("skl_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SkillId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skill");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("42c49e3d-04b5-4170-b54a-454e1098e583"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5872),
                            Disabled = false,
                            Name = "C#"
                        },
                        new
                        {
                            SkillId = new Guid("206f2ad1-1e59-4d6f-b4d2-adf35ff2bde1"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5879),
                            Disabled = false,
                            Name = "Java"
                        },
                        new
                        {
                            SkillId = new Guid("1dfad6db-abd2-4934-98d0-7085e71e726e"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5883),
                            Disabled = false,
                            Name = "Python"
                        },
                        new
                        {
                            SkillId = new Guid("05dfbf95-f148-4fe3-9f94-f77283b76671"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5887),
                            Disabled = false,
                            Name = "JavaScript"
                        },
                        new
                        {
                            SkillId = new Guid("5f4b6904-ef66-4e11-935c-935bfd451c0f"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5890),
                            Disabled = false,
                            Name = "TypeScript"
                        },
                        new
                        {
                            SkillId = new Guid("d23b6fae-f053-4ca6-bbc8-90e1d18de802"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5895),
                            Disabled = false,
                            Name = "HTML"
                        },
                        new
                        {
                            SkillId = new Guid("2d621e4b-fba2-4edc-88d5-1243470e76b5"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5899),
                            Disabled = false,
                            Name = "CSS"
                        },
                        new
                        {
                            SkillId = new Guid("33b8611d-a42e-4633-b3fd-cf3ad6467102"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5902),
                            Disabled = false,
                            Name = "SQL"
                        },
                        new
                        {
                            SkillId = new Guid("26b03419-4faa-4692-a814-d62a3f36b524"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5906),
                            Disabled = false,
                            Name = "NoSQL"
                        },
                        new
                        {
                            SkillId = new Guid("f2d97931-27bb-40aa-a416-a3082cd0c269"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5910),
                            Disabled = false,
                            Name = "Angular"
                        },
                        new
                        {
                            SkillId = new Guid("33f5e1cf-67cc-4216-9da0-d9cb638ea755"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5917),
                            Disabled = false,
                            Name = "React"
                        },
                        new
                        {
                            SkillId = new Guid("4a3fbea4-7ae8-4a07-98b2-f85de812d4fe"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5918),
                            Disabled = false,
                            Name = "Vue"
                        },
                        new
                        {
                            SkillId = new Guid("d11d465e-0483-45f7-bd05-acb459927f8d"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5921),
                            Disabled = false,
                            Name = "Node.js"
                        },
                        new
                        {
                            SkillId = new Guid("1930cd62-0f85-4e54-aa6b-d512bd5f3abd"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5925),
                            Disabled = false,
                            Name = "Spring Boot"
                        },
                        new
                        {
                            SkillId = new Guid("087f671c-e1e1-4011-b395-5968674f32af"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 5, 25, 463, DateTimeKind.Utc).AddTicks(5929),
                            Disabled = false,
                            Name = "Hibernate"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.SubSkillModel", b =>
                {
                    b.Property<Guid>("SubSkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("sbskl_subskill_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("sbskl_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sbskl_name");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skl_skill_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SubSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("Name", "SkillId")
                        .IsUnique();

                    b.ToTable("subskill");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CityModel", b =>
                {
                    b.HasOne("Profiles.Infrastructure.Persistence.Models.ProvinceModel", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.HasOne("Profiles.Infrastructure.Persistence.Models.CountryModel", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.SubSkillModel", b =>
                {
                    b.HasOne("Profiles.Infrastructure.Persistence.Models.SkillModel", "Skill")
                        .WithMany("SubSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CountryModel", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.SkillModel", b =>
                {
                    b.Navigation("SubSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
