// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Profiles.Infrastructure.Persistence;

#nullable disable

namespace Profiles.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240608025755_Tables")]
    partial class Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CityModel", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("cty_city_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("cty_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cty_name");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("prv_province_id");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("Name", "ProvinceId")
                        .IsUnique();

                    b.ToTable("city");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("9039321f-b78a-4e48-b1fa-935c86e7bfe8"),
                            Disabled = false,
                            Name = "Leticia",
                            ProvinceId = new Guid("8f5d4d86-b4aa-4866-94ad-e5e97687a007")
                        },
                        new
                        {
                            CityId = new Guid("ea5ee31a-8b85-4a10-80b1-e506e79a1868"),
                            Disabled = false,
                            Name = "Medellín",
                            ProvinceId = new Guid("40425c6e-abe2-439a-aa3a-b4fba23eb116")
                        },
                        new
                        {
                            CityId = new Guid("5102c375-a52f-447e-9e3c-6da75c033ebe"),
                            Disabled = false,
                            Name = "Apartadó",
                            ProvinceId = new Guid("40425c6e-abe2-439a-aa3a-b4fba23eb116")
                        },
                        new
                        {
                            CityId = new Guid("4024b1a5-2059-460e-ab5b-d582bd885c8c"),
                            Disabled = false,
                            Name = "Turbo",
                            ProvinceId = new Guid("40425c6e-abe2-439a-aa3a-b4fba23eb116")
                        },
                        new
                        {
                            CityId = new Guid("b02a3b3e-3f44-4c4e-a063-a7cebfce6ac1"),
                            Disabled = false,
                            Name = "Arauca",
                            ProvinceId = new Guid("60ad0eca-a433-4952-aedd-a5af106257e5")
                        },
                        new
                        {
                            CityId = new Guid("e8676e7f-0294-4952-b3f6-c9f790e15447"),
                            Disabled = false,
                            Name = "Saravena",
                            ProvinceId = new Guid("60ad0eca-a433-4952-aedd-a5af106257e5")
                        },
                        new
                        {
                            CityId = new Guid("285c1155-7cf6-4479-aac1-7373832811a1"),
                            Disabled = false,
                            Name = "Fortul",
                            ProvinceId = new Guid("60ad0eca-a433-4952-aedd-a5af106257e5")
                        },
                        new
                        {
                            CityId = new Guid("f960c663-5459-4339-a591-a19dd6013417"),
                            Disabled = false,
                            Name = "Barranquilla",
                            ProvinceId = new Guid("0b0d286b-21c2-4d1d-9745-17d9c2e529f7")
                        },
                        new
                        {
                            CityId = new Guid("d2bc1ce3-d9c7-4fe4-a743-765dfc94a62d"),
                            Disabled = false,
                            Name = "Soledad",
                            ProvinceId = new Guid("0b0d286b-21c2-4d1d-9745-17d9c2e529f7")
                        },
                        new
                        {
                            CityId = new Guid("8972349d-e55a-4bd9-8133-1bc756b961fe"),
                            Disabled = false,
                            Name = "Puerto Colombia",
                            ProvinceId = new Guid("0b0d286b-21c2-4d1d-9745-17d9c2e529f7")
                        },
                        new
                        {
                            CityId = new Guid("64d14d20-23f3-417b-80f6-3dc9f135514f"),
                            Disabled = false,
                            Name = "Cartagena de Indias",
                            ProvinceId = new Guid("aa2d2d92-3024-427f-81b9-6aec0b305a8a")
                        },
                        new
                        {
                            CityId = new Guid("96402fe4-6820-41e8-8c1b-a9dbb978d7dc"),
                            Disabled = false,
                            Name = "Magangué",
                            ProvinceId = new Guid("aa2d2d92-3024-427f-81b9-6aec0b305a8a")
                        },
                        new
                        {
                            CityId = new Guid("cf4708ac-78d8-4de1-9766-e4bc61044e6f"),
                            Disabled = false,
                            Name = "Cartagena del Chairá",
                            ProvinceId = new Guid("aa2d2d92-3024-427f-81b9-6aec0b305a8a")
                        },
                        new
                        {
                            CityId = new Guid("cf0580a4-26b0-4cb4-8a18-66f58204191e"),
                            Disabled = false,
                            Name = "Tunja",
                            ProvinceId = new Guid("4fbe7a63-ce0d-485e-b360-d94aa7a3c23e")
                        },
                        new
                        {
                            CityId = new Guid("72f5f57f-cd3f-4797-beb7-f9ee1df44cc9"),
                            Disabled = false,
                            Name = "Sogamoso",
                            ProvinceId = new Guid("4fbe7a63-ce0d-485e-b360-d94aa7a3c23e")
                        },
                        new
                        {
                            CityId = new Guid("f60b00b4-8ad2-4cb2-a7eb-edf3cb2fb849"),
                            Disabled = false,
                            Name = "Duitama",
                            ProvinceId = new Guid("4fbe7a63-ce0d-485e-b360-d94aa7a3c23e")
                        },
                        new
                        {
                            CityId = new Guid("835acef0-74b6-40c7-9da4-e37536f1e237"),
                            Disabled = false,
                            Name = "Manizales",
                            ProvinceId = new Guid("662befe1-f710-4694-9c85-b9c29dc05fa0")
                        },
                        new
                        {
                            CityId = new Guid("f2ead246-6c29-4554-aff9-18155e906bd7"),
                            Disabled = false,
                            Name = "Pereira",
                            ProvinceId = new Guid("662befe1-f710-4694-9c85-b9c29dc05fa0")
                        },
                        new
                        {
                            CityId = new Guid("a0a181bb-e070-4131-9df3-959ebe53410e"),
                            Disabled = false,
                            Name = "Chinchiná",
                            ProvinceId = new Guid("662befe1-f710-4694-9c85-b9c29dc05fa0")
                        },
                        new
                        {
                            CityId = new Guid("cc8193f4-f0f5-42c2-85f2-fe57b28f9ab1"),
                            Disabled = false,
                            Name = "Florencia",
                            ProvinceId = new Guid("eda9dc13-c0fe-42eb-ad4c-c5a7573ca4cf")
                        },
                        new
                        {
                            CityId = new Guid("e5be225a-860b-4657-874f-3f7c155790c0"),
                            Disabled = false,
                            Name = "Cartagena del Chairá",
                            ProvinceId = new Guid("eda9dc13-c0fe-42eb-ad4c-c5a7573ca4cf")
                        },
                        new
                        {
                            CityId = new Guid("699e5c05-634c-4774-80e7-e634d1dcacd1"),
                            Disabled = false,
                            Name = "Morelia",
                            ProvinceId = new Guid("eda9dc13-c0fe-42eb-ad4c-c5a7573ca4cf")
                        },
                        new
                        {
                            CityId = new Guid("5e30eb43-d01a-446c-99d0-f653cc080b64"),
                            Disabled = false,
                            Name = "Yopal",
                            ProvinceId = new Guid("f34f9f4c-44a2-40b0-a391-17182d6fcc67")
                        },
                        new
                        {
                            CityId = new Guid("cee7985f-fca2-4277-b849-8eafcf2521e4"),
                            Disabled = false,
                            Name = "Aguazul",
                            ProvinceId = new Guid("f34f9f4c-44a2-40b0-a391-17182d6fcc67")
                        },
                        new
                        {
                            CityId = new Guid("47a0a287-52cb-460b-9f33-4025b47ba771"),
                            Disabled = false,
                            Name = "Tauramena",
                            ProvinceId = new Guid("f34f9f4c-44a2-40b0-a391-17182d6fcc67")
                        },
                        new
                        {
                            CityId = new Guid("d10cc2b7-7a42-459e-836b-e13071b44bc1"),
                            Disabled = false,
                            Name = "Popayán",
                            ProvinceId = new Guid("822cac7a-c804-4ba1-8d73-abfeaf566272")
                        },
                        new
                        {
                            CityId = new Guid("35a86551-b845-47d9-95ac-dc23b14246c8"),
                            Disabled = false,
                            Name = "Silvia",
                            ProvinceId = new Guid("822cac7a-c804-4ba1-8d73-abfeaf566272")
                        },
                        new
                        {
                            CityId = new Guid("79ab8d32-f2ef-42d5-b80a-dd92ac61add7"),
                            Disabled = false,
                            Name = "Santander de Quilichao",
                            ProvinceId = new Guid("822cac7a-c804-4ba1-8d73-abfeaf566272")
                        },
                        new
                        {
                            CityId = new Guid("fcb2570e-a518-49f3-a93b-d982dd035c5a"),
                            Disabled = false,
                            Name = "Valledupar",
                            ProvinceId = new Guid("99a295e3-9403-41c2-bc92-f52ef186e7e3")
                        },
                        new
                        {
                            CityId = new Guid("5ec86bb0-a3a8-4762-9dd3-f091a4b8b7ae"),
                            Disabled = false,
                            Name = "Aguachica",
                            ProvinceId = new Guid("99a295e3-9403-41c2-bc92-f52ef186e7e3")
                        },
                        new
                        {
                            CityId = new Guid("9051e15a-4df0-4832-b42f-bdf220118905"),
                            Disabled = false,
                            Name = "La Paz",
                            ProvinceId = new Guid("99a295e3-9403-41c2-bc92-f52ef186e7e3")
                        },
                        new
                        {
                            CityId = new Guid("a85036b4-2bad-4408-982d-e3345ded617a"),
                            Disabled = false,
                            Name = "Quibdó",
                            ProvinceId = new Guid("7d20ff47-fb82-4bec-9c91-cb3c0e28a9ec")
                        },
                        new
                        {
                            CityId = new Guid("dd196bca-8114-40ba-b512-f779a55a0711"),
                            Disabled = false,
                            Name = "Istmina",
                            ProvinceId = new Guid("7d20ff47-fb82-4bec-9c91-cb3c0e28a9ec")
                        },
                        new
                        {
                            CityId = new Guid("2ba73d98-cb1f-4521-9975-aa47f5c4edcc"),
                            Disabled = false,
                            Name = "Novita",
                            ProvinceId = new Guid("7d20ff47-fb82-4bec-9c91-cb3c0e28a9ec")
                        },
                        new
                        {
                            CityId = new Guid("53da6ea1-f9a1-4b6c-a6f5-48133d0e99dd"),
                            Disabled = false,
                            Name = "Montería",
                            ProvinceId = new Guid("deaa059e-a368-4592-8ad9-2fc9a710fb4f")
                        },
                        new
                        {
                            CityId = new Guid("5624d836-c8ac-4d93-91fc-2ee931989599"),
                            Disabled = false,
                            Name = "Cereté",
                            ProvinceId = new Guid("deaa059e-a368-4592-8ad9-2fc9a710fb4f")
                        },
                        new
                        {
                            CityId = new Guid("291d777f-b85e-4a0e-9083-661c953a1739"),
                            Disabled = false,
                            Name = "Lorica",
                            ProvinceId = new Guid("deaa059e-a368-4592-8ad9-2fc9a710fb4f")
                        },
                        new
                        {
                            CityId = new Guid("ba153edd-5d6e-4513-a6b7-86de605feac9"),
                            Disabled = false,
                            Name = "Bogotá",
                            ProvinceId = new Guid("4503b414-9297-4d41-9d34-43002159eab7")
                        },
                        new
                        {
                            CityId = new Guid("279a1cb3-03d2-434f-ab33-4beabbdda034"),
                            Disabled = false,
                            Name = "Soacha",
                            ProvinceId = new Guid("4503b414-9297-4d41-9d34-43002159eab7")
                        },
                        new
                        {
                            CityId = new Guid("9d63c49d-2a42-4d12-bc2b-39f49e526ed0"),
                            Disabled = false,
                            Name = "Zipaquirá",
                            ProvinceId = new Guid("4503b414-9297-4d41-9d34-43002159eab7")
                        },
                        new
                        {
                            CityId = new Guid("6d57907c-9277-4b4c-b29e-d1d81ce52640"),
                            Disabled = false,
                            Name = "Inírida",
                            ProvinceId = new Guid("4ea7cf1e-51b9-485d-bf6e-8fc2f6775e7c")
                        },
                        new
                        {
                            CityId = new Guid("b3dd69ef-c6c3-409e-8606-64cd8280251c"),
                            Disabled = false,
                            Name = "Puerto Inírida",
                            ProvinceId = new Guid("4ea7cf1e-51b9-485d-bf6e-8fc2f6775e7c")
                        },
                        new
                        {
                            CityId = new Guid("74faff0d-6e8b-4f52-a723-e95ca352bfee"),
                            Disabled = false,
                            Name = "Memarí",
                            ProvinceId = new Guid("4ea7cf1e-51b9-485d-bf6e-8fc2f6775e7c")
                        },
                        new
                        {
                            CityId = new Guid("c002b03e-ea2a-4d3c-ba8a-85c7d4da3eaa"),
                            Disabled = false,
                            Name = "San José del Guaviare",
                            ProvinceId = new Guid("49782e32-f95a-4917-9861-0085faaa7b50")
                        },
                        new
                        {
                            CityId = new Guid("6bd8ed28-fbd1-47bd-8479-3321b1abb9d4"),
                            Disabled = false,
                            Name = "Calamar",
                            ProvinceId = new Guid("49782e32-f95a-4917-9861-0085faaa7b50")
                        },
                        new
                        {
                            CityId = new Guid("ea7ed149-4f87-4c94-93c7-8c239338c27d"),
                            Disabled = false,
                            Name = "El Retén",
                            ProvinceId = new Guid("49782e32-f95a-4917-9861-0085faaa7b50")
                        },
                        new
                        {
                            CityId = new Guid("00d72140-cdaa-4baf-8c80-6c82ac827f86"),
                            Disabled = false,
                            Name = "Neiva",
                            ProvinceId = new Guid("9f363aca-fb3f-4708-aef7-659190d7c141")
                        },
                        new
                        {
                            CityId = new Guid("c45abb3c-a7ab-4a27-9bb6-0456cb5d31d6"),
                            Disabled = false,
                            Name = "Garzón",
                            ProvinceId = new Guid("9f363aca-fb3f-4708-aef7-659190d7c141")
                        },
                        new
                        {
                            CityId = new Guid("4b59a662-738a-4f73-aad7-f5cebaab5d48"),
                            Disabled = false,
                            Name = "Pitalito",
                            ProvinceId = new Guid("9f363aca-fb3f-4708-aef7-659190d7c141")
                        },
                        new
                        {
                            CityId = new Guid("d86d70aa-ab8b-4e3c-bd32-b9610f65aad8"),
                            Disabled = false,
                            Name = "Riohacha",
                            ProvinceId = new Guid("b8f089af-8038-4b8b-ad22-b189ec19aefc")
                        },
                        new
                        {
                            CityId = new Guid("c79fc35e-40b8-48d1-96a4-c1845b6f3835"),
                            Disabled = false,
                            Name = "Maicao",
                            ProvinceId = new Guid("b8f089af-8038-4b8b-ad22-b189ec19aefc")
                        },
                        new
                        {
                            CityId = new Guid("6c44ac90-43be-4775-9833-6e5b5adfd976"),
                            Disabled = false,
                            Name = "Uribia",
                            ProvinceId = new Guid("b8f089af-8038-4b8b-ad22-b189ec19aefc")
                        },
                        new
                        {
                            CityId = new Guid("79683241-c743-47ff-b417-5079192af532"),
                            Disabled = false,
                            Name = "Santa Marta",
                            ProvinceId = new Guid("a367ce45-d4a6-4520-9906-1870d5849ab8")
                        },
                        new
                        {
                            CityId = new Guid("de9c90ac-66e9-468f-ac28-afa7e686003b"),
                            Disabled = false,
                            Name = "Aracataca",
                            ProvinceId = new Guid("a367ce45-d4a6-4520-9906-1870d5849ab8")
                        },
                        new
                        {
                            CityId = new Guid("debb3353-58f3-4f88-97d4-7c3d0cf01f2f"),
                            Disabled = false,
                            Name = "Ciénaga",
                            ProvinceId = new Guid("a367ce45-d4a6-4520-9906-1870d5849ab8")
                        },
                        new
                        {
                            CityId = new Guid("8647b653-d58c-42b2-ba80-4df110cafe8a"),
                            Disabled = false,
                            Name = "Villavicencio",
                            ProvinceId = new Guid("209e5d47-00ed-4249-959d-f89d6749160a")
                        },
                        new
                        {
                            CityId = new Guid("300d49d5-2704-4966-9047-4698962e4a6a"),
                            Disabled = false,
                            Name = "Acacias",
                            ProvinceId = new Guid("209e5d47-00ed-4249-959d-f89d6749160a")
                        },
                        new
                        {
                            CityId = new Guid("a557af9f-7ebe-4332-b2ff-13e2596e77b2"),
                            Disabled = false,
                            Name = "Granada",
                            ProvinceId = new Guid("209e5d47-00ed-4249-959d-f89d6749160a")
                        },
                        new
                        {
                            CityId = new Guid("da7528d2-4b30-4c94-9069-8810b1b80786"),
                            Disabled = false,
                            Name = "San Juan de Pasto",
                            ProvinceId = new Guid("f9e082fa-0dee-41eb-aa67-02fddb3a0b3d")
                        },
                        new
                        {
                            CityId = new Guid("8fb5f0d2-aedf-42f3-944f-7d4a3ae29c21"),
                            Disabled = false,
                            Name = "Tumaco",
                            ProvinceId = new Guid("f9e082fa-0dee-41eb-aa67-02fddb3a0b3d")
                        },
                        new
                        {
                            CityId = new Guid("a6f0dfec-57a2-407f-8064-6c32456bb7fb"),
                            Disabled = false,
                            Name = "Ipiales",
                            ProvinceId = new Guid("f9e082fa-0dee-41eb-aa67-02fddb3a0b3d")
                        },
                        new
                        {
                            CityId = new Guid("15335391-d37f-4a3c-bc96-5e617bf51dae"),
                            Disabled = false,
                            Name = "Cúcuta",
                            ProvinceId = new Guid("40d8ebf1-ad2c-4ae1-987c-09280f659383")
                        },
                        new
                        {
                            CityId = new Guid("915c6fcc-b4bf-4aae-91b1-8d1f30f5a1b5"),
                            Disabled = false,
                            Name = "Ocaña",
                            ProvinceId = new Guid("40d8ebf1-ad2c-4ae1-987c-09280f659383")
                        },
                        new
                        {
                            CityId = new Guid("1d0d7908-e074-4a50-b052-2317217d45d5"),
                            Disabled = false,
                            Name = "Pamplona",
                            ProvinceId = new Guid("40d8ebf1-ad2c-4ae1-987c-09280f659383")
                        },
                        new
                        {
                            CityId = new Guid("5e89c1f8-dea0-4568-9fbc-bf3059ae1c7f"),
                            Disabled = false,
                            Name = "Mocoa",
                            ProvinceId = new Guid("3a76b9cf-39ec-48c9-9508-50f17df3b382")
                        },
                        new
                        {
                            CityId = new Guid("cce88514-1a7a-494a-b41d-27098c329f2c"),
                            Disabled = false,
                            Name = "Puerto Asís",
                            ProvinceId = new Guid("3a76b9cf-39ec-48c9-9508-50f17df3b382")
                        },
                        new
                        {
                            CityId = new Guid("a58b3009-619e-4997-854a-cba87fdddb03"),
                            Disabled = false,
                            Name = "Orito",
                            ProvinceId = new Guid("3a76b9cf-39ec-48c9-9508-50f17df3b382")
                        },
                        new
                        {
                            CityId = new Guid("4e977c21-8c15-4b6a-906f-24f80ad88daf"),
                            Disabled = false,
                            Name = "Armenia",
                            ProvinceId = new Guid("d68a25e8-59b0-4754-a240-5982fe7d773d")
                        },
                        new
                        {
                            CityId = new Guid("42a61ce2-5e01-4caf-b261-ebc8491196ee"),
                            Disabled = false,
                            Name = "Calarcá",
                            ProvinceId = new Guid("d68a25e8-59b0-4754-a240-5982fe7d773d")
                        },
                        new
                        {
                            CityId = new Guid("71623e0a-a26d-4f65-a270-b8a9355eea35"),
                            Disabled = false,
                            Name = "La Tebaida",
                            ProvinceId = new Guid("d68a25e8-59b0-4754-a240-5982fe7d773d")
                        },
                        new
                        {
                            CityId = new Guid("be7270e3-411c-4afa-93de-ef519ee877d8"),
                            Disabled = false,
                            Name = "Pereira",
                            ProvinceId = new Guid("27599624-570d-43ba-9cea-ff41a017fe07")
                        },
                        new
                        {
                            CityId = new Guid("98b0e775-a45e-4164-a55f-c1149982a636"),
                            Disabled = false,
                            Name = "Dosquebradas",
                            ProvinceId = new Guid("27599624-570d-43ba-9cea-ff41a017fe07")
                        },
                        new
                        {
                            CityId = new Guid("eb732d1a-f794-43ff-a121-abec2b49e659"),
                            Disabled = false,
                            Name = "Santa Rosa de Cabal",
                            ProvinceId = new Guid("27599624-570d-43ba-9cea-ff41a017fe07")
                        },
                        new
                        {
                            CityId = new Guid("925f2b24-5d8e-4d75-9013-cd18047d3d79"),
                            Disabled = false,
                            Name = "San Andrés",
                            ProvinceId = new Guid("1e73edf9-f423-475e-a9eb-d400485e7c60")
                        },
                        new
                        {
                            CityId = new Guid("bac2f6e8-d80c-491f-8b92-c0b8516e1166"),
                            Disabled = false,
                            Name = "Providencia",
                            ProvinceId = new Guid("1e73edf9-f423-475e-a9eb-d400485e7c60")
                        },
                        new
                        {
                            CityId = new Guid("5f94a23e-1b29-4953-8f16-15d9b76b5e1e"),
                            Disabled = false,
                            Name = "Santa Catalina",
                            ProvinceId = new Guid("1e73edf9-f423-475e-a9eb-d400485e7c60")
                        },
                        new
                        {
                            CityId = new Guid("e0789df1-f055-4d6c-a048-2c8d89cfc8e3"),
                            Disabled = false,
                            Name = "Bucaramanga",
                            ProvinceId = new Guid("5463bf9a-732a-4602-a13a-953e41d83619")
                        },
                        new
                        {
                            CityId = new Guid("7ec9d0d6-c5a5-4f90-8c4c-5ecbe6d210eb"),
                            Disabled = false,
                            Name = "Barrancabermeja",
                            ProvinceId = new Guid("5463bf9a-732a-4602-a13a-953e41d83619")
                        },
                        new
                        {
                            CityId = new Guid("c1125531-5bc8-47c8-9df0-a81838b26aa5"),
                            Disabled = false,
                            Name = "Piedecuesta",
                            ProvinceId = new Guid("5463bf9a-732a-4602-a13a-953e41d83619")
                        },
                        new
                        {
                            CityId = new Guid("07f2076d-f0c7-4679-acb0-858e6640bdd9"),
                            Disabled = false,
                            Name = "Sincelejo",
                            ProvinceId = new Guid("3b9322e8-e71f-477c-a51b-7d57092d5576")
                        },
                        new
                        {
                            CityId = new Guid("826278e2-cbeb-454e-93b9-85ee824450a8"),
                            Disabled = false,
                            Name = "Corozal",
                            ProvinceId = new Guid("3b9322e8-e71f-477c-a51b-7d57092d5576")
                        },
                        new
                        {
                            CityId = new Guid("a0182ba2-97ea-4358-8707-36a2e516448a"),
                            Disabled = false,
                            Name = "Montería",
                            ProvinceId = new Guid("3b9322e8-e71f-477c-a51b-7d57092d5576")
                        },
                        new
                        {
                            CityId = new Guid("81919357-bb36-4a90-b044-3330daa6d904"),
                            Disabled = false,
                            Name = "Ibagué",
                            ProvinceId = new Guid("3700be94-0cb0-493d-bd59-38a72b1cc5b4")
                        },
                        new
                        {
                            CityId = new Guid("99229636-9537-4851-8e7b-4bfd1dc14c17"),
                            Disabled = false,
                            Name = "Honda",
                            ProvinceId = new Guid("3700be94-0cb0-493d-bd59-38a72b1cc5b4")
                        },
                        new
                        {
                            CityId = new Guid("814716bb-78f9-4f5c-af5b-ff1f1fd281fb"),
                            Disabled = false,
                            Name = "Armero Guayabal",
                            ProvinceId = new Guid("3700be94-0cb0-493d-bd59-38a72b1cc5b4")
                        },
                        new
                        {
                            CityId = new Guid("fdc18df1-1b0c-4bf0-9e86-044d192945f0"),
                            Disabled = false,
                            Name = "Cali",
                            ProvinceId = new Guid("82308b5d-7eb2-418c-bfa5-ccb118bfa337")
                        },
                        new
                        {
                            CityId = new Guid("02c81ef9-1454-4e47-b4fc-7d1a03174e22"),
                            Disabled = false,
                            Name = "Palmira",
                            ProvinceId = new Guid("82308b5d-7eb2-418c-bfa5-ccb118bfa337")
                        },
                        new
                        {
                            CityId = new Guid("d22d9893-fbd5-4722-a573-50981eb275d1"),
                            Disabled = false,
                            Name = "Buenaventura",
                            ProvinceId = new Guid("82308b5d-7eb2-418c-bfa5-ccb118bfa337")
                        },
                        new
                        {
                            CityId = new Guid("2c1a5cc0-24e1-4fe5-87ae-675dd4fcd0bb"),
                            Disabled = false,
                            Name = "Mitú",
                            ProvinceId = new Guid("04bccc12-133f-4ea4-bf00-28a0024d1c36")
                        },
                        new
                        {
                            CityId = new Guid("56dc6f8f-c13c-4217-95c6-7880439b46f2"),
                            Disabled = false,
                            Name = "Yavaraté",
                            ProvinceId = new Guid("04bccc12-133f-4ea4-bf00-28a0024d1c36")
                        },
                        new
                        {
                            CityId = new Guid("e846a9d4-601e-49c6-85ba-9e47a92d3eb7"),
                            Disabled = false,
                            Name = "Santa Rosalía",
                            ProvinceId = new Guid("04bccc12-133f-4ea4-bf00-28a0024d1c36")
                        },
                        new
                        {
                            CityId = new Guid("8413c7bc-7b41-48ce-8a5d-ffb7d8ab7f93"),
                            Disabled = false,
                            Name = "Puerto Carreño",
                            ProvinceId = new Guid("ca6c39e0-7fa8-42a7-9239-e9c0fb648c72")
                        },
                        new
                        {
                            CityId = new Guid("9037104d-bb09-4002-84d9-5289720c3dcb"),
                            Disabled = false,
                            Name = "La Primavera",
                            ProvinceId = new Guid("ca6c39e0-7fa8-42a7-9239-e9c0fb648c72")
                        },
                        new
                        {
                            CityId = new Guid("5884024c-5366-4cd3-b3fa-e41a8f1234ba"),
                            Disabled = false,
                            Name = "Santa Helena",
                            ProvinceId = new Guid("ca6c39e0-7fa8-42a7-9239-e9c0fb648c72")
                        },
                        new
                        {
                            CityId = new Guid("7f5358f2-a49f-40a9-9e9c-e9132a9c176a"),
                            Disabled = false,
                            Name = "Cuenca",
                            ProvinceId = new Guid("bf9117f5-6bce-486f-85ad-4de512cfe53d")
                        },
                        new
                        {
                            CityId = new Guid("4553f716-0047-4a36-86f6-54d66716c366"),
                            Disabled = false,
                            Name = "Girón",
                            ProvinceId = new Guid("bf9117f5-6bce-486f-85ad-4de512cfe53d")
                        },
                        new
                        {
                            CityId = new Guid("6a7b93e5-a7f8-4f1c-b3ba-8cefe96ab38a"),
                            Disabled = false,
                            Name = "Guaranda",
                            ProvinceId = new Guid("efc9342f-749d-4529-ac1c-22733c4b61c3")
                        },
                        new
                        {
                            CityId = new Guid("1a93a42a-1b3e-498f-811a-ec5263fbf8c1"),
                            Disabled = false,
                            Name = "San Miguel de Bolívar",
                            ProvinceId = new Guid("efc9342f-749d-4529-ac1c-22733c4b61c3")
                        },
                        new
                        {
                            CityId = new Guid("b884efa7-efea-4118-8cf0-3651fe8cba46"),
                            Disabled = false,
                            Name = "Azogues",
                            ProvinceId = new Guid("58a11708-f5ed-4884-8366-46e06dc72f63")
                        },
                        new
                        {
                            CityId = new Guid("8ed69b27-3bd7-4ac6-9278-41d2ca756121"),
                            Disabled = false,
                            Name = "El Tambo",
                            ProvinceId = new Guid("58a11708-f5ed-4884-8366-46e06dc72f63")
                        },
                        new
                        {
                            CityId = new Guid("34a9c78d-82a7-4487-8ae0-30789803df63"),
                            Disabled = false,
                            Name = "Tulcán",
                            ProvinceId = new Guid("c3039b7b-8f5a-44d1-ba4d-baf273109172")
                        },
                        new
                        {
                            CityId = new Guid("9b279167-741d-46a6-8a5d-f4df72c62876"),
                            Disabled = false,
                            Name = "El Guabo",
                            ProvinceId = new Guid("c3039b7b-8f5a-44d1-ba4d-baf273109172")
                        },
                        new
                        {
                            CityId = new Guid("9a63273e-6e5b-46ce-833a-7b7cdf56d5ce"),
                            Disabled = false,
                            Name = "Riobamba",
                            ProvinceId = new Guid("f951b8bb-bda3-4b02-af6a-2fb4e6cd22b6")
                        },
                        new
                        {
                            CityId = new Guid("5a5140f5-6932-4f98-ad0c-dc6b2945f093"),
                            Disabled = false,
                            Name = "Alausí",
                            ProvinceId = new Guid("f951b8bb-bda3-4b02-af6a-2fb4e6cd22b6")
                        },
                        new
                        {
                            CityId = new Guid("b3647420-ba95-4785-948f-3c8f68ed8aa0"),
                            Disabled = false,
                            Name = "Latacunga",
                            ProvinceId = new Guid("d0f96ade-df12-46c7-9c82-cd63377b99e2")
                        },
                        new
                        {
                            CityId = new Guid("6be2afca-a890-4b01-af73-206f47274708"),
                            Disabled = false,
                            Name = "Salcedo",
                            ProvinceId = new Guid("d0f96ade-df12-46c7-9c82-cd63377b99e2")
                        },
                        new
                        {
                            CityId = new Guid("9ede208a-22bb-40d3-af1c-4a5a5cdce485"),
                            Disabled = false,
                            Name = "Machala",
                            ProvinceId = new Guid("f8c6d5db-408f-4792-b5c2-dc7902174404")
                        },
                        new
                        {
                            CityId = new Guid("a42970a2-ae87-43d5-9a23-18577390ea0f"),
                            Disabled = false,
                            Name = "Santa Rosa",
                            ProvinceId = new Guid("f8c6d5db-408f-4792-b5c2-dc7902174404")
                        },
                        new
                        {
                            CityId = new Guid("f955b475-aa16-4916-822a-25c9cb48f6d8"),
                            Disabled = false,
                            Name = "Esmeraldas",
                            ProvinceId = new Guid("a800fe30-6d9c-4a67-a47f-6a4eda3ddf44")
                        },
                        new
                        {
                            CityId = new Guid("1af6389c-de63-4269-96f6-684701aaed3b"),
                            Disabled = false,
                            Name = "Atacames",
                            ProvinceId = new Guid("a800fe30-6d9c-4a67-a47f-6a4eda3ddf44")
                        },
                        new
                        {
                            CityId = new Guid("00fe986c-7a2d-4df7-9117-90b7d97640c2"),
                            Disabled = false,
                            Name = "Puerto Baquerizo Moreno",
                            ProvinceId = new Guid("83535988-f964-4b9d-9588-baca6c784626")
                        },
                        new
                        {
                            CityId = new Guid("d5965130-6cb2-41fb-af13-9164667cf0c0"),
                            Disabled = false,
                            Name = "San Cristóbal",
                            ProvinceId = new Guid("83535988-f964-4b9d-9588-baca6c784626")
                        },
                        new
                        {
                            CityId = new Guid("0ebad736-47c0-405f-bd14-7c79d59c1da5"),
                            Disabled = false,
                            Name = "Guayaquil",
                            ProvinceId = new Guid("35d56e0d-03b3-4a19-8757-9a32f2b5723b")
                        },
                        new
                        {
                            CityId = new Guid("c8c47225-4ebf-4a36-a1c2-c81247d5670d"),
                            Disabled = false,
                            Name = "Durán",
                            ProvinceId = new Guid("35d56e0d-03b3-4a19-8757-9a32f2b5723b")
                        },
                        new
                        {
                            CityId = new Guid("c2a06c70-df14-4c96-a730-7e0942a830d9"),
                            Disabled = false,
                            Name = "Ibarra",
                            ProvinceId = new Guid("e877f38c-67e2-41e8-ab85-3ced74d81b85")
                        },
                        new
                        {
                            CityId = new Guid("804b3784-b89b-455e-bb84-4b6f3754d418"),
                            Disabled = false,
                            Name = "Otavalo",
                            ProvinceId = new Guid("e877f38c-67e2-41e8-ab85-3ced74d81b85")
                        },
                        new
                        {
                            CityId = new Guid("355d19bf-c03f-4feb-a747-473ff93ca9aa"),
                            Disabled = false,
                            Name = "Loja",
                            ProvinceId = new Guid("4b9c2826-84f5-4bff-a941-d5387f54f5d7")
                        },
                        new
                        {
                            CityId = new Guid("eae94c57-365f-4132-8dd0-eb85d5996216"),
                            Disabled = false,
                            Name = "Saraguro",
                            ProvinceId = new Guid("4b9c2826-84f5-4bff-a941-d5387f54f5d7")
                        },
                        new
                        {
                            CityId = new Guid("47f950ce-6e93-4ff5-a92e-0e334fd05bc0"),
                            Disabled = false,
                            Name = "Portoviejo",
                            ProvinceId = new Guid("aec548aa-8d4e-4558-a99b-ef67e6eb338a")
                        },
                        new
                        {
                            CityId = new Guid("11ee36be-c308-41b3-8959-12e18b6b0905"),
                            Disabled = false,
                            Name = "Manta",
                            ProvinceId = new Guid("aec548aa-8d4e-4558-a99b-ef67e6eb338a")
                        },
                        new
                        {
                            CityId = new Guid("6e3b484d-b559-4256-8ff7-5cccbfcf4571"),
                            Disabled = false,
                            Name = "Chone",
                            ProvinceId = new Guid("aec548aa-8d4e-4558-a99b-ef67e6eb338a")
                        },
                        new
                        {
                            CityId = new Guid("e2719014-95a7-4703-9f6e-8b69d0e79e87"),
                            Disabled = false,
                            Name = "Macas",
                            ProvinceId = new Guid("1e0db1d1-9a57-4322-a623-35bc676df01b")
                        },
                        new
                        {
                            CityId = new Guid("ceeafd04-be9b-44b0-a3d7-ba6e37a821ed"),
                            Disabled = false,
                            Name = "Gualaquiza",
                            ProvinceId = new Guid("1e0db1d1-9a57-4322-a623-35bc676df01b")
                        },
                        new
                        {
                            CityId = new Guid("ff65e481-3745-4153-b625-0d9b9c2cc9af"),
                            Disabled = false,
                            Name = "Tena",
                            ProvinceId = new Guid("329b9370-522b-4919-982f-0702b9fc965f")
                        },
                        new
                        {
                            CityId = new Guid("b81f73d5-b654-4535-a2ed-8634651aa36c"),
                            Disabled = false,
                            Name = "Archidona",
                            ProvinceId = new Guid("329b9370-522b-4919-982f-0702b9fc965f")
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CountryModel", b =>
                {
                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ctr_country_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("ctr_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctr_name");

                    b.HasKey("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("country");

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Colombia"
                        },
                        new
                        {
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Ecuador"
                        },
                        new
                        {
                            CountryId = new Guid("267c889a-414e-4a8c-9615-defa70730cd1"),
                            Disabled = false,
                            Name = "Venezuela"
                        },
                        new
                        {
                            CountryId = new Guid("2ab9785d-1dc7-4722-8e44-ce176ca3e666"),
                            Disabled = false,
                            Name = "Panamá"
                        },
                        new
                        {
                            CountryId = new Guid("d0c1adc8-092a-46ed-aee0-d2e18e30f97d"),
                            Disabled = false,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            CountryId = new Guid("58d00d84-9e9e-40cf-aa25-c7cea37bdecd"),
                            Disabled = false,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            CountryId = new Guid("dec48fd2-d568-472a-bcad-90636ec1fefb"),
                            Disabled = false,
                            Name = "Honduras"
                        },
                        new
                        {
                            CountryId = new Guid("0c5438c6-88f6-4f40-8c3a-92ca0fd77fa0"),
                            Disabled = false,
                            Name = "Guatemala"
                        },
                        new
                        {
                            CountryId = new Guid("85252b8c-3eac-4e3b-9fd6-a269e7546815"),
                            Disabled = false,
                            Name = "El Salvador"
                        },
                        new
                        {
                            CountryId = new Guid("0560cc93-05d4-4560-ac35-4c3273d8d2f7"),
                            Disabled = false,
                            Name = "Belize"
                        },
                        new
                        {
                            CountryId = new Guid("f6ff1d7a-72ba-420f-9152-1954e095daad"),
                            Disabled = false,
                            Name = "México"
                        },
                        new
                        {
                            CountryId = new Guid("17b9f73e-54d9-4d88-a205-b7c19e45cffc"),
                            Disabled = false,
                            Name = "Perú"
                        },
                        new
                        {
                            CountryId = new Guid("9dce4008-8006-4e4e-b12e-5d8dfa49ee02"),
                            Disabled = false,
                            Name = "Chile"
                        },
                        new
                        {
                            CountryId = new Guid("c2ad2be1-fc82-47d9-a369-d3f07c31e98b"),
                            Disabled = false,
                            Name = "Argentina"
                        },
                        new
                        {
                            CountryId = new Guid("05447922-05c2-4493-8692-55aa2e128e62"),
                            Disabled = false,
                            Name = "Brasil"
                        },
                        new
                        {
                            CountryId = new Guid("c314ad3f-002f-4256-8ba8-78e279f48f04"),
                            Disabled = false,
                            Name = "Paraguay"
                        },
                        new
                        {
                            CountryId = new Guid("d0d34c3f-fad7-4205-b001-de989db421af"),
                            Disabled = false,
                            Name = "Uruguay"
                        },
                        new
                        {
                            CountryId = new Guid("b8c23550-59ab-4d2d-9e8e-18d5decd835a"),
                            Disabled = false,
                            Name = "Bolivia"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.LevelModel", b =>
                {
                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_level_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rol_description");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("rol_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("LevelId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("level");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProfessionalModel", b =>
                {
                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("prf_professional_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("prf_disabled");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prf_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prf_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProfessionalId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("professional");

                    b.HasData(
                        new
                        {
                            ProfessionalId = new Guid("862edcda-3d9c-436d-b804-2d5a3444fa38"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7052),
                            Disabled = false,
                            Email = "juanperez@gmail.com",
                            Name = "Juan Pérez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("b982dc75-976a-49e6-8eae-295f3ed51d30"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7058),
                            Disabled = false,
                            Email = "mariagarcia@gmail.com",
                            Name = "María García"
                        },
                        new
                        {
                            ProfessionalId = new Guid("3ef1a9fc-df06-4b68-9a23-effac3c330ce"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7062),
                            Disabled = false,
                            Email = "pedrolopez@gmail.com",
                            Name = "Pedro López"
                        },
                        new
                        {
                            ProfessionalId = new Guid("1b1160b9-6090-4bde-82e2-0f31295a4f38"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7065),
                            Disabled = false,
                            Email = "anasanchez@gmail.com",
                            Name = "Ana Sánchez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("f087fb4f-7c42-4bfb-9e7c-2d11939289d3"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7069),
                            Disabled = false,
                            Email = "carlosrodriguez@gmail.com",
                            Name = "Carlos Rodríguez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("0f8aaebe-d0c2-4319-ab44-66309cdf5bbe"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7074),
                            Disabled = false,
                            Email = "isabelmartinez@gmail.com",
                            Name = "Isabel Martínez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("8d0e207d-4ae1-4695-829d-a65d0da28637"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7077),
                            Disabled = false,
                            Email = "diegogomez@gmail.com",
                            Name = "Diego Gómez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("de7d1824-28b0-4dad-bf49-92bd68e83579"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7081),
                            Disabled = false,
                            Email = "sandramoreno@gmail.com",
                            Name = "Sandra Moreno"
                        },
                        new
                        {
                            ProfessionalId = new Guid("08cd8bb8-8f8e-44ca-bb67-ecac500d170a"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7085),
                            Disabled = false,
                            Email = "andresfernandez@gmail.com",
                            Name = "Andrés Fernández"
                        },
                        new
                        {
                            ProfessionalId = new Guid("e04e1904-83dd-4e0d-97ac-480f968a8fe9"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7089),
                            Disabled = false,
                            Email = "lauragonzalez@gmail.com",
                            Name = "Laura González"
                        },
                        new
                        {
                            ProfessionalId = new Guid("7914a0f1-4020-4c2e-840d-a389cbdafb8b"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7093),
                            Disabled = false,
                            Email = "javiermunoz@gmail.com",
                            Name = "Javier Muñoz"
                        },
                        new
                        {
                            ProfessionalId = new Guid("32dda917-7e4b-4cdb-b2c9-7728234ef374"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7097),
                            Disabled = false,
                            Email = "patriciablanco@gmail.com",
                            Name = "Patricia Blanco"
                        },
                        new
                        {
                            ProfessionalId = new Guid("a08f9a78-4853-4542-8378-a788fff5ee38"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7100),
                            Disabled = false,
                            Email = "josegutierrez@gmail.com",
                            Name = "José Gutiérrez"
                        },
                        new
                        {
                            ProfessionalId = new Guid("1f8d99d6-9fd3-4118-9395-6609b0d21cf9"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7104),
                            Disabled = false,
                            Email = "aliciaruis@gmail.com",
                            Name = "Alicia Ruiz"
                        },
                        new
                        {
                            ProfessionalId = new Guid("a56ad525-83db-42c7-a9eb-ead1b23dc2f6"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(7108),
                            Disabled = false,
                            Email = "luisvazquez@gmail.com",
                            Name = "Luis Vázquez"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("prv_province_id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ctr_country_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("prv_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prv_name");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name", "CountryId")
                        .IsUnique();

                    b.ToTable("province");

                    b.HasData(
                        new
                        {
                            ProvinceId = new Guid("8f5d4d86-b4aa-4866-94ad-e5e97687a007"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Amazonas"
                        },
                        new
                        {
                            ProvinceId = new Guid("40425c6e-abe2-439a-aa3a-b4fba23eb116"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Antioquia"
                        },
                        new
                        {
                            ProvinceId = new Guid("60ad0eca-a433-4952-aedd-a5af106257e5"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Arauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("0b0d286b-21c2-4d1d-9745-17d9c2e529f7"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Atlántico"
                        },
                        new
                        {
                            ProvinceId = new Guid("aa2d2d92-3024-427f-81b9-6aec0b305a8a"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Bolívar"
                        },
                        new
                        {
                            ProvinceId = new Guid("4fbe7a63-ce0d-485e-b360-d94aa7a3c23e"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Boyacá"
                        },
                        new
                        {
                            ProvinceId = new Guid("662befe1-f710-4694-9c85-b9c29dc05fa0"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Caldas"
                        },
                        new
                        {
                            ProvinceId = new Guid("eda9dc13-c0fe-42eb-ad4c-c5a7573ca4cf"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Caquetá"
                        },
                        new
                        {
                            ProvinceId = new Guid("f34f9f4c-44a2-40b0-a391-17182d6fcc67"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Casanare"
                        },
                        new
                        {
                            ProvinceId = new Guid("822cac7a-c804-4ba1-8d73-abfeaf566272"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Cauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("99a295e3-9403-41c2-bc92-f52ef186e7e3"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Cesar"
                        },
                        new
                        {
                            ProvinceId = new Guid("7d20ff47-fb82-4bec-9c91-cb3c0e28a9ec"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Chocó"
                        },
                        new
                        {
                            ProvinceId = new Guid("deaa059e-a368-4592-8ad9-2fc9a710fb4f"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Córdoba"
                        },
                        new
                        {
                            ProvinceId = new Guid("4503b414-9297-4d41-9d34-43002159eab7"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Cundinamarca"
                        },
                        new
                        {
                            ProvinceId = new Guid("4ea7cf1e-51b9-485d-bf6e-8fc2f6775e7c"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Guainía"
                        },
                        new
                        {
                            ProvinceId = new Guid("49782e32-f95a-4917-9861-0085faaa7b50"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Guaviare"
                        },
                        new
                        {
                            ProvinceId = new Guid("9f363aca-fb3f-4708-aef7-659190d7c141"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Huila"
                        },
                        new
                        {
                            ProvinceId = new Guid("b8f089af-8038-4b8b-ad22-b189ec19aefc"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "La Guajira"
                        },
                        new
                        {
                            ProvinceId = new Guid("a367ce45-d4a6-4520-9906-1870d5849ab8"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Magdalena"
                        },
                        new
                        {
                            ProvinceId = new Guid("209e5d47-00ed-4249-959d-f89d6749160a"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Meta"
                        },
                        new
                        {
                            ProvinceId = new Guid("f9e082fa-0dee-41eb-aa67-02fddb3a0b3d"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Nariño"
                        },
                        new
                        {
                            ProvinceId = new Guid("40d8ebf1-ad2c-4ae1-987c-09280f659383"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Norte de Santander"
                        },
                        new
                        {
                            ProvinceId = new Guid("3a76b9cf-39ec-48c9-9508-50f17df3b382"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Putumayo"
                        },
                        new
                        {
                            ProvinceId = new Guid("d68a25e8-59b0-4754-a240-5982fe7d773d"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Quindío"
                        },
                        new
                        {
                            ProvinceId = new Guid("27599624-570d-43ba-9cea-ff41a017fe07"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Risaralda"
                        },
                        new
                        {
                            ProvinceId = new Guid("1e73edf9-f423-475e-a9eb-d400485e7c60"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "San Andrés y Providencia"
                        },
                        new
                        {
                            ProvinceId = new Guid("5463bf9a-732a-4602-a13a-953e41d83619"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Santander"
                        },
                        new
                        {
                            ProvinceId = new Guid("3b9322e8-e71f-477c-a51b-7d57092d5576"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Sucre"
                        },
                        new
                        {
                            ProvinceId = new Guid("3700be94-0cb0-493d-bd59-38a72b1cc5b4"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Tolima"
                        },
                        new
                        {
                            ProvinceId = new Guid("82308b5d-7eb2-418c-bfa5-ccb118bfa337"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Valle del Cauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("04bccc12-133f-4ea4-bf00-28a0024d1c36"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Vaupés"
                        },
                        new
                        {
                            ProvinceId = new Guid("ca6c39e0-7fa8-42a7-9239-e9c0fb648c72"),
                            CountryId = new Guid("4e67acf7-8f38-48b1-af88-5df6451fa4c6"),
                            Disabled = false,
                            Name = "Vichada"
                        },
                        new
                        {
                            ProvinceId = new Guid("bf9117f5-6bce-486f-85ad-4de512cfe53d"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Azuay"
                        },
                        new
                        {
                            ProvinceId = new Guid("efc9342f-749d-4529-ac1c-22733c4b61c3"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Bolívar"
                        },
                        new
                        {
                            ProvinceId = new Guid("58a11708-f5ed-4884-8366-46e06dc72f63"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Cañar"
                        },
                        new
                        {
                            ProvinceId = new Guid("c3039b7b-8f5a-44d1-ba4d-baf273109172"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Carchi"
                        },
                        new
                        {
                            ProvinceId = new Guid("f951b8bb-bda3-4b02-af6a-2fb4e6cd22b6"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Chimborazo"
                        },
                        new
                        {
                            ProvinceId = new Guid("d0f96ade-df12-46c7-9c82-cd63377b99e2"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Cotopaxi"
                        },
                        new
                        {
                            ProvinceId = new Guid("f8c6d5db-408f-4792-b5c2-dc7902174404"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "El Oro"
                        },
                        new
                        {
                            ProvinceId = new Guid("a800fe30-6d9c-4a67-a47f-6a4eda3ddf44"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Esmeraldas"
                        },
                        new
                        {
                            ProvinceId = new Guid("83535988-f964-4b9d-9588-baca6c784626"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Galápagos"
                        },
                        new
                        {
                            ProvinceId = new Guid("35d56e0d-03b3-4a19-8757-9a32f2b5723b"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Guayas"
                        },
                        new
                        {
                            ProvinceId = new Guid("e877f38c-67e2-41e8-ab85-3ced74d81b85"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Imbabura"
                        },
                        new
                        {
                            ProvinceId = new Guid("4b9c2826-84f5-4bff-a941-d5387f54f5d7"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Loja"
                        },
                        new
                        {
                            ProvinceId = new Guid("aec548aa-8d4e-4558-a99b-ef67e6eb338a"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Manabí"
                        },
                        new
                        {
                            ProvinceId = new Guid("1e0db1d1-9a57-4322-a623-35bc676df01b"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Morona Santiago"
                        },
                        new
                        {
                            ProvinceId = new Guid("329b9370-522b-4919-982f-0702b9fc965f"),
                            CountryId = new Guid("1e1dcb29-8d4b-4e26-9678-a51735898a61"),
                            Disabled = false,
                            Name = "Napo"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.RoleModel", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_role_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rol_description");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("rol_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("role");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("4ef97d56-b67b-45d1-b5b8-f51d2d159396"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6868),
                            Disabled = false,
                            Name = "Developer"
                        },
                        new
                        {
                            RoleId = new Guid("9c1fa9b2-41a9-4c82-9348-8779df44b7b5"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6879),
                            Disabled = false,
                            Name = "Designer"
                        },
                        new
                        {
                            RoleId = new Guid("ed8e1c3e-1ae9-4d06-867a-86c9f2bf5968"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6883),
                            Disabled = false,
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = new Guid("ab4b6739-49b3-486e-9b0b-0626943631ce"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6887),
                            Disabled = false,
                            Name = "QA"
                        },
                        new
                        {
                            RoleId = new Guid("732986a3-5923-4799-ab34-e866b6ec1f44"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6891),
                            Disabled = false,
                            Name = "DevOps"
                        },
                        new
                        {
                            RoleId = new Guid("ef6f3038-725f-466b-95af-df0616ca2282"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6895),
                            Disabled = false,
                            Name = "Data Scientist"
                        },
                        new
                        {
                            RoleId = new Guid("d28600cb-eb0d-419d-841a-47adcb5debff"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6899),
                            Disabled = false,
                            Name = "UX/UI Designer"
                        },
                        new
                        {
                            RoleId = new Guid("c21da06e-9edc-4082-a526-276ab7000ca7"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6903),
                            Disabled = false,
                            Name = "Product Owner"
                        },
                        new
                        {
                            RoleId = new Guid("d1eb0ee7-7341-4019-8524-80b9c5b478dc"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6906),
                            Disabled = false,
                            Name = "Scrum Master"
                        },
                        new
                        {
                            RoleId = new Guid("e282d090-0cd3-411c-838a-a78746aa5d78"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6911),
                            Disabled = false,
                            Name = "Architect"
                        },
                        new
                        {
                            RoleId = new Guid("792fd8ad-5d88-4a4a-ba83-01edfc13973b"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6914),
                            Disabled = false,
                            Name = "Lead Developer"
                        },
                        new
                        {
                            RoleId = new Guid("23dd81e4-0d67-43d0-b236-d2e4341574ef"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6918),
                            Disabled = false,
                            Name = "Lead Designer"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.SkillModel", b =>
                {
                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skl_skill_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("skl_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("skl_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SkillId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skill");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("4821fb22-612c-4665-9ed4-df3cf5d9fa08"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6940),
                            Disabled = false,
                            Name = "C#"
                        },
                        new
                        {
                            SkillId = new Guid("177127c7-0073-46f3-bac4-1c864df4073c"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6946),
                            Disabled = false,
                            Name = "Java"
                        },
                        new
                        {
                            SkillId = new Guid("78e1a3e5-fa3f-4e3a-bf38-7778c7713ced"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6950),
                            Disabled = false,
                            Name = "Python"
                        },
                        new
                        {
                            SkillId = new Guid("e93c6419-d2db-44ef-83b8-c45481639864"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6954),
                            Disabled = false,
                            Name = "JavaScript"
                        },
                        new
                        {
                            SkillId = new Guid("c78142fa-834f-4f3b-bec7-1063076a1f00"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6958),
                            Disabled = false,
                            Name = "TypeScript"
                        },
                        new
                        {
                            SkillId = new Guid("8c48f59d-8c2a-4b58-96d5-a59fcbc1c725"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6962),
                            Disabled = false,
                            Name = "HTML"
                        },
                        new
                        {
                            SkillId = new Guid("4b5c5993-0b25-4ae9-ba62-202fc15edeb5"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6966),
                            Disabled = false,
                            Name = "CSS"
                        },
                        new
                        {
                            SkillId = new Guid("cf3865b3-2b79-409c-96cd-1c0971b40a0a"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6969),
                            Disabled = false,
                            Name = "SQL"
                        },
                        new
                        {
                            SkillId = new Guid("35ecef44-aa03-43b1-8f3e-f83b9cd38c85"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6973),
                            Disabled = false,
                            Name = "NoSQL"
                        },
                        new
                        {
                            SkillId = new Guid("b5b84739-2c46-49ea-a73a-f02a53731ba6"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6977),
                            Disabled = false,
                            Name = "Angular"
                        },
                        new
                        {
                            SkillId = new Guid("a71ad0df-f8e6-45d9-9a57-8e50e6c95301"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6984),
                            Disabled = false,
                            Name = "React"
                        },
                        new
                        {
                            SkillId = new Guid("e6423792-7924-4ce7-8c5f-0a4dbe0c5bf9"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6984),
                            Disabled = false,
                            Name = "Vue"
                        },
                        new
                        {
                            SkillId = new Guid("4f196ca3-6239-4006-936b-e3529c17bd40"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6988),
                            Disabled = false,
                            Name = "Node.js"
                        },
                        new
                        {
                            SkillId = new Guid("c0b4678b-d297-4ab7-a53c-03c2c9e11ffa"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6991),
                            Disabled = false,
                            Name = "Spring Boot"
                        },
                        new
                        {
                            SkillId = new Guid("b2b78da4-873b-49cf-8dc7-cb31fc1f1218"),
                            CreatedAt = new DateTime(2024, 6, 8, 2, 57, 55, 700, DateTimeKind.Utc).AddTicks(6995),
                            Disabled = false,
                            Name = "Hibernate"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.SquadModel", b =>
                {
                    b.Property<Guid>("SquadId")
                        .HasColumnType("uuid")
                        .HasColumnName("sqd_squad_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("sqd_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sqd_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SquadId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("squad");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.SubSkillModel", b =>
                {
                    b.Property<Guid>("SubSkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("sbskl_subskill_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("sbskl_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sbskl_name");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skl_skill_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SubSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("Name", "SkillId")
                        .IsUnique();

                    b.ToTable("subskill");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CityModel", b =>
                {
                    b.HasOne("Profiles.Infrastructure.Persistence.Models.ProvinceModel", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.HasOne("Profiles.Infrastructure.Persistence.Models.CountryModel", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.SubSkillModel", b =>
                {
                    b.HasOne("Profiles.Infrastructure.Persistence.Models.SkillModel", "Skill")
                        .WithMany("SubSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CountryModel", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.SkillModel", b =>
                {
                    b.Navigation("SubSkills");
                });
#pragma warning restore 612, 618
        }
    }
}

