// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Profiles.Infrastructure.Persistence;

#nullable disable

namespace Profiles.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240427041329_Data1")]
    partial class Data1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CityModel", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("cty_city_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("cty_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cty_name");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("prv_province_id");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("tbl_city");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("0d3a78b7-9748-4980-881f-ca52e9a4fd44"),
                            Disabled = false,
                            Name = "Leticia",
                            ProvinceId = new Guid("ce5e384b-aba3-419f-b44a-838d14fef4d4")
                        },
                        new
                        {
                            CityId = new Guid("481db274-cb9b-4288-b865-3d1cb4ac8130"),
                            Disabled = false,
                            Name = "Medellín",
                            ProvinceId = new Guid("f54ef90c-652d-4b02-84bd-a59922663c0d")
                        },
                        new
                        {
                            CityId = new Guid("25d40856-cf7a-4819-9a0a-a321a43e0991"),
                            Disabled = false,
                            Name = "Apartadó",
                            ProvinceId = new Guid("f54ef90c-652d-4b02-84bd-a59922663c0d")
                        },
                        new
                        {
                            CityId = new Guid("13f5a516-b244-488f-a263-363126e216b3"),
                            Disabled = false,
                            Name = "Turbo",
                            ProvinceId = new Guid("f54ef90c-652d-4b02-84bd-a59922663c0d")
                        },
                        new
                        {
                            CityId = new Guid("7d98eb82-5857-4e54-b11f-fd8d135bab61"),
                            Disabled = false,
                            Name = "Arauca",
                            ProvinceId = new Guid("e9a5d171-872f-433a-b2f8-387d4bd0f7da")
                        },
                        new
                        {
                            CityId = new Guid("179c0d95-4c35-40ea-8ac4-17ee2bd63cbc"),
                            Disabled = false,
                            Name = "Saravena",
                            ProvinceId = new Guid("e9a5d171-872f-433a-b2f8-387d4bd0f7da")
                        },
                        new
                        {
                            CityId = new Guid("ac638403-2b43-4bc2-a373-458908c81d52"),
                            Disabled = false,
                            Name = "Fortul",
                            ProvinceId = new Guid("e9a5d171-872f-433a-b2f8-387d4bd0f7da")
                        },
                        new
                        {
                            CityId = new Guid("1b045edd-0593-4cc1-8bc9-10d58063c258"),
                            Disabled = false,
                            Name = "Barranquilla",
                            ProvinceId = new Guid("ccd1f1e8-5362-47f3-b756-45638205937e")
                        },
                        new
                        {
                            CityId = new Guid("b84a2656-37f9-41d9-96c3-953df1fff6bb"),
                            Disabled = false,
                            Name = "Soledad",
                            ProvinceId = new Guid("ccd1f1e8-5362-47f3-b756-45638205937e")
                        },
                        new
                        {
                            CityId = new Guid("799ef8ad-e489-491a-a9f1-8f87afe95df5"),
                            Disabled = false,
                            Name = "Puerto Colombia",
                            ProvinceId = new Guid("ccd1f1e8-5362-47f3-b756-45638205937e")
                        },
                        new
                        {
                            CityId = new Guid("9c4c67d6-0691-4475-ac9f-3228b7a7f0ec"),
                            Disabled = false,
                            Name = "Cartagena de Indias",
                            ProvinceId = new Guid("1bd8ee39-acfc-4698-af69-50482e771bf8")
                        },
                        new
                        {
                            CityId = new Guid("a5c64622-8acd-4ae6-8bcb-8c36d79d3468"),
                            Disabled = false,
                            Name = "Magangué",
                            ProvinceId = new Guid("1bd8ee39-acfc-4698-af69-50482e771bf8")
                        },
                        new
                        {
                            CityId = new Guid("a2c932b8-603c-49ef-80fb-c720be803be7"),
                            Disabled = false,
                            Name = "Cartagena del Chairá",
                            ProvinceId = new Guid("1bd8ee39-acfc-4698-af69-50482e771bf8")
                        },
                        new
                        {
                            CityId = new Guid("255cd525-d9f7-4ec0-b80b-3aaa74ef7996"),
                            Disabled = false,
                            Name = "Tunja",
                            ProvinceId = new Guid("f04849cf-b20f-4b68-ba5c-d530860e877a")
                        },
                        new
                        {
                            CityId = new Guid("afabcce2-8dde-4411-989f-671d36333b07"),
                            Disabled = false,
                            Name = "Sogamoso",
                            ProvinceId = new Guid("f04849cf-b20f-4b68-ba5c-d530860e877a")
                        },
                        new
                        {
                            CityId = new Guid("851c754b-103a-4349-a317-1c3d2945a4fd"),
                            Disabled = false,
                            Name = "Duitama",
                            ProvinceId = new Guid("f04849cf-b20f-4b68-ba5c-d530860e877a")
                        },
                        new
                        {
                            CityId = new Guid("fdfb1d69-7b34-4446-ac7f-0d07d2fbf8f8"),
                            Disabled = false,
                            Name = "Manizales",
                            ProvinceId = new Guid("fe6f20de-70e1-4e93-8bf9-1a7a9c52b4e3")
                        },
                        new
                        {
                            CityId = new Guid("3b08acfc-0f80-4dc3-b6de-22c5355bb396"),
                            Disabled = false,
                            Name = "Pereira",
                            ProvinceId = new Guid("fe6f20de-70e1-4e93-8bf9-1a7a9c52b4e3")
                        },
                        new
                        {
                            CityId = new Guid("ff206d7e-c40d-4a0f-b96c-ef3068c47f2f"),
                            Disabled = false,
                            Name = "Chinchiná",
                            ProvinceId = new Guid("fe6f20de-70e1-4e93-8bf9-1a7a9c52b4e3")
                        },
                        new
                        {
                            CityId = new Guid("d2d5e823-de27-4c01-94d9-f683aaf2c328"),
                            Disabled = false,
                            Name = "Florencia",
                            ProvinceId = new Guid("389cc7dd-b657-47cf-91d9-03bb7a07a387")
                        },
                        new
                        {
                            CityId = new Guid("4d469620-1d69-46bb-ba2f-e079b7ec2522"),
                            Disabled = false,
                            Name = "Cartagena del Chairá",
                            ProvinceId = new Guid("389cc7dd-b657-47cf-91d9-03bb7a07a387")
                        },
                        new
                        {
                            CityId = new Guid("3c5024a1-7af5-4b32-b606-ce14e5119afc"),
                            Disabled = false,
                            Name = "Morelia",
                            ProvinceId = new Guid("389cc7dd-b657-47cf-91d9-03bb7a07a387")
                        },
                        new
                        {
                            CityId = new Guid("ae8a1214-a04d-4946-bdba-cfe9a13344a0"),
                            Disabled = false,
                            Name = "Yopal",
                            ProvinceId = new Guid("ddc81f77-5305-40c9-af13-c79f5b11651f")
                        },
                        new
                        {
                            CityId = new Guid("d2a88e9a-56e1-4be2-8b07-8795752f9514"),
                            Disabled = false,
                            Name = "Aguazul",
                            ProvinceId = new Guid("ddc81f77-5305-40c9-af13-c79f5b11651f")
                        },
                        new
                        {
                            CityId = new Guid("2fba9e64-05ef-4115-a696-cea384b4d316"),
                            Disabled = false,
                            Name = "Tauramena",
                            ProvinceId = new Guid("ddc81f77-5305-40c9-af13-c79f5b11651f")
                        },
                        new
                        {
                            CityId = new Guid("22785934-2b8b-4c15-8c6b-7cac71e7683d"),
                            Disabled = false,
                            Name = "Popayán",
                            ProvinceId = new Guid("d58ad120-0875-471b-a094-9bf4f9614501")
                        },
                        new
                        {
                            CityId = new Guid("5442606c-2813-4ddf-a8df-c3af215026ab"),
                            Disabled = false,
                            Name = "Silvia",
                            ProvinceId = new Guid("d58ad120-0875-471b-a094-9bf4f9614501")
                        },
                        new
                        {
                            CityId = new Guid("3280138e-5210-4a36-b5bb-16ee5e2b37aa"),
                            Disabled = false,
                            Name = "Santander de Quilichao",
                            ProvinceId = new Guid("d58ad120-0875-471b-a094-9bf4f9614501")
                        },
                        new
                        {
                            CityId = new Guid("a53524a6-fd40-46e7-b65e-e4294711ef7b"),
                            Disabled = false,
                            Name = "Valledupar",
                            ProvinceId = new Guid("8899a64c-cb80-4e17-ae51-6138202c80b1")
                        },
                        new
                        {
                            CityId = new Guid("d075788c-2dec-4853-b6c7-eee49bffd002"),
                            Disabled = false,
                            Name = "Aguachica",
                            ProvinceId = new Guid("8899a64c-cb80-4e17-ae51-6138202c80b1")
                        },
                        new
                        {
                            CityId = new Guid("399c336e-0757-4744-b887-28cfe237a122"),
                            Disabled = false,
                            Name = "La Paz",
                            ProvinceId = new Guid("8899a64c-cb80-4e17-ae51-6138202c80b1")
                        },
                        new
                        {
                            CityId = new Guid("9cb18f45-f483-407f-a777-9f5065ea8b96"),
                            Disabled = false,
                            Name = "Quibdó",
                            ProvinceId = new Guid("20703693-f1e1-47df-aced-f2fb026121f0")
                        },
                        new
                        {
                            CityId = new Guid("b027cf51-af86-4d0c-839f-4ad9f90c1d2f"),
                            Disabled = false,
                            Name = "Istmina",
                            ProvinceId = new Guid("20703693-f1e1-47df-aced-f2fb026121f0")
                        },
                        new
                        {
                            CityId = new Guid("7ca6476c-f743-44fb-8315-462255835295"),
                            Disabled = false,
                            Name = "Novita",
                            ProvinceId = new Guid("20703693-f1e1-47df-aced-f2fb026121f0")
                        },
                        new
                        {
                            CityId = new Guid("5b65889b-5cc9-48a2-a2a1-b9009517ea35"),
                            Disabled = false,
                            Name = "Montería",
                            ProvinceId = new Guid("881810ca-5d93-4a0a-adb6-1938069d7b83")
                        },
                        new
                        {
                            CityId = new Guid("ca225c9a-388e-4109-886b-5858c0724e0a"),
                            Disabled = false,
                            Name = "Cereté",
                            ProvinceId = new Guid("881810ca-5d93-4a0a-adb6-1938069d7b83")
                        },
                        new
                        {
                            CityId = new Guid("1544c036-b337-4f38-855d-83e58a1000ca"),
                            Disabled = false,
                            Name = "Lorica",
                            ProvinceId = new Guid("881810ca-5d93-4a0a-adb6-1938069d7b83")
                        },
                        new
                        {
                            CityId = new Guid("65319d15-395a-40ae-bd7a-8255fc5fa655"),
                            Disabled = false,
                            Name = "Bogotá",
                            ProvinceId = new Guid("58989ded-a4de-4b43-a8af-3edcc83a3a93")
                        },
                        new
                        {
                            CityId = new Guid("3cc178c7-6c76-40df-b2cc-1603a9fe3b6e"),
                            Disabled = false,
                            Name = "Soacha",
                            ProvinceId = new Guid("58989ded-a4de-4b43-a8af-3edcc83a3a93")
                        },
                        new
                        {
                            CityId = new Guid("bce2166c-4c0e-4a20-8d98-c65440bff943"),
                            Disabled = false,
                            Name = "Zipaquirá",
                            ProvinceId = new Guid("58989ded-a4de-4b43-a8af-3edcc83a3a93")
                        },
                        new
                        {
                            CityId = new Guid("7574eb5f-521c-422c-bc90-5ab108c2b114"),
                            Disabled = false,
                            Name = "Inírida",
                            ProvinceId = new Guid("9130e757-5e7d-4a02-9177-3740c9d9a1d8")
                        },
                        new
                        {
                            CityId = new Guid("59cdcd53-7c79-4ee5-a008-838ba369aaa4"),
                            Disabled = false,
                            Name = "Puerto Inírida",
                            ProvinceId = new Guid("9130e757-5e7d-4a02-9177-3740c9d9a1d8")
                        },
                        new
                        {
                            CityId = new Guid("2191c05b-91e1-467b-8479-31b125c9794b"),
                            Disabled = false,
                            Name = "Memarí",
                            ProvinceId = new Guid("9130e757-5e7d-4a02-9177-3740c9d9a1d8")
                        },
                        new
                        {
                            CityId = new Guid("2c84ddae-25b8-4927-bb54-f8eff025f2df"),
                            Disabled = false,
                            Name = "San José del Guaviare",
                            ProvinceId = new Guid("1b489446-0ac4-466f-ad8b-33401107e38e")
                        },
                        new
                        {
                            CityId = new Guid("3028b426-7a77-4104-8add-9e724846e43b"),
                            Disabled = false,
                            Name = "Calamar",
                            ProvinceId = new Guid("1b489446-0ac4-466f-ad8b-33401107e38e")
                        },
                        new
                        {
                            CityId = new Guid("7a002051-e080-4cc7-8a18-7f5817384ba0"),
                            Disabled = false,
                            Name = "El Retén",
                            ProvinceId = new Guid("1b489446-0ac4-466f-ad8b-33401107e38e")
                        },
                        new
                        {
                            CityId = new Guid("61fc82fb-4666-4475-98a8-b689d4697c32"),
                            Disabled = false,
                            Name = "Neiva",
                            ProvinceId = new Guid("d5903001-75aa-4019-b730-77d39df3bc9f")
                        },
                        new
                        {
                            CityId = new Guid("fa3cf363-f986-41d0-8c33-c06c923e8651"),
                            Disabled = false,
                            Name = "Garzón",
                            ProvinceId = new Guid("d5903001-75aa-4019-b730-77d39df3bc9f")
                        },
                        new
                        {
                            CityId = new Guid("cd963eec-60c4-49ec-b889-a843bb05e692"),
                            Disabled = false,
                            Name = "Pitalito",
                            ProvinceId = new Guid("d5903001-75aa-4019-b730-77d39df3bc9f")
                        },
                        new
                        {
                            CityId = new Guid("91c519c4-caeb-4c50-9dde-6732138881ba"),
                            Disabled = false,
                            Name = "Riohacha",
                            ProvinceId = new Guid("c51dbd19-e282-478e-bd00-5c0fe649f22c")
                        },
                        new
                        {
                            CityId = new Guid("32a59e02-520b-495a-966c-21840b69efcd"),
                            Disabled = false,
                            Name = "Maicao",
                            ProvinceId = new Guid("c51dbd19-e282-478e-bd00-5c0fe649f22c")
                        },
                        new
                        {
                            CityId = new Guid("e09babeb-337c-49aa-a045-2e5a4306bf1c"),
                            Disabled = false,
                            Name = "Uribia",
                            ProvinceId = new Guid("c51dbd19-e282-478e-bd00-5c0fe649f22c")
                        },
                        new
                        {
                            CityId = new Guid("c2c14bdf-69da-499c-bf83-330606eec7d5"),
                            Disabled = false,
                            Name = "Santa Marta",
                            ProvinceId = new Guid("f0abb4fa-14a1-4029-93e4-378bd229e68f")
                        },
                        new
                        {
                            CityId = new Guid("fc943944-12a6-4247-a127-6c08fc9cb8ad"),
                            Disabled = false,
                            Name = "Aracataca",
                            ProvinceId = new Guid("f0abb4fa-14a1-4029-93e4-378bd229e68f")
                        },
                        new
                        {
                            CityId = new Guid("f8540489-9171-4f3a-807b-4818e8019fdc"),
                            Disabled = false,
                            Name = "Ciénaga",
                            ProvinceId = new Guid("f0abb4fa-14a1-4029-93e4-378bd229e68f")
                        },
                        new
                        {
                            CityId = new Guid("42f44b93-efb1-489d-aa74-60c3cf6260b4"),
                            Disabled = false,
                            Name = "Villavicencio",
                            ProvinceId = new Guid("786717f0-a4a6-4610-bf16-8b602f868a66")
                        },
                        new
                        {
                            CityId = new Guid("0fe38acc-f285-45a1-8dfb-35194a2c5ade"),
                            Disabled = false,
                            Name = "Acacias",
                            ProvinceId = new Guid("786717f0-a4a6-4610-bf16-8b602f868a66")
                        },
                        new
                        {
                            CityId = new Guid("96b3e15d-3e64-47b4-ba27-c1a36d11cbef"),
                            Disabled = false,
                            Name = "Granada",
                            ProvinceId = new Guid("786717f0-a4a6-4610-bf16-8b602f868a66")
                        },
                        new
                        {
                            CityId = new Guid("72cbd880-fcb1-4545-b4ca-fdcb9b4d621b"),
                            Disabled = false,
                            Name = "San Juan de Pasto",
                            ProvinceId = new Guid("5e1af82f-834e-4caa-bfb7-cd92d08c92d6")
                        },
                        new
                        {
                            CityId = new Guid("620fa1c2-63ee-4f70-b4e0-a65c4f770b1f"),
                            Disabled = false,
                            Name = "Tumaco",
                            ProvinceId = new Guid("5e1af82f-834e-4caa-bfb7-cd92d08c92d6")
                        },
                        new
                        {
                            CityId = new Guid("2eaca892-fed7-4cd7-80fa-7d40c6cbb33f"),
                            Disabled = false,
                            Name = "Ipiales",
                            ProvinceId = new Guid("5e1af82f-834e-4caa-bfb7-cd92d08c92d6")
                        },
                        new
                        {
                            CityId = new Guid("67e6d8c0-fb3a-4ec6-aacc-8db78d63c3de"),
                            Disabled = false,
                            Name = "Cúcuta",
                            ProvinceId = new Guid("ccda11b3-cbfc-4039-bf79-8a45e0bd6a3d")
                        },
                        new
                        {
                            CityId = new Guid("c483c76c-764e-4fac-afd4-71e829b7051a"),
                            Disabled = false,
                            Name = "Ocaña",
                            ProvinceId = new Guid("ccda11b3-cbfc-4039-bf79-8a45e0bd6a3d")
                        },
                        new
                        {
                            CityId = new Guid("c55c1f6f-a272-4d1e-b701-ddec13d9730c"),
                            Disabled = false,
                            Name = "Pamplona",
                            ProvinceId = new Guid("ccda11b3-cbfc-4039-bf79-8a45e0bd6a3d")
                        },
                        new
                        {
                            CityId = new Guid("805eb4ce-b9f6-490b-9593-d39c1bec8caa"),
                            Disabled = false,
                            Name = "Mocoa",
                            ProvinceId = new Guid("090758f1-8666-4bb5-89f0-db8e154cee56")
                        },
                        new
                        {
                            CityId = new Guid("bcb666c4-ecf7-44bd-814b-b7b93a709018"),
                            Disabled = false,
                            Name = "Puerto Asís",
                            ProvinceId = new Guid("090758f1-8666-4bb5-89f0-db8e154cee56")
                        },
                        new
                        {
                            CityId = new Guid("3c5d44b7-5a5e-4f9a-bca7-443f8ac3756c"),
                            Disabled = false,
                            Name = "Orito",
                            ProvinceId = new Guid("090758f1-8666-4bb5-89f0-db8e154cee56")
                        },
                        new
                        {
                            CityId = new Guid("e0d9f4f6-531f-41a0-bfc6-92a2a2098ae4"),
                            Disabled = false,
                            Name = "Armenia",
                            ProvinceId = new Guid("b7f674a8-94fe-4ec1-8611-1b5c48ea2e27")
                        },
                        new
                        {
                            CityId = new Guid("dd0865f2-b9fb-4fdc-903c-15a86ba3d174"),
                            Disabled = false,
                            Name = "Calarcá",
                            ProvinceId = new Guid("b7f674a8-94fe-4ec1-8611-1b5c48ea2e27")
                        },
                        new
                        {
                            CityId = new Guid("fe6de2fb-cc0d-4d18-ae16-e7afd31f9f0b"),
                            Disabled = false,
                            Name = "La Tebaida",
                            ProvinceId = new Guid("b7f674a8-94fe-4ec1-8611-1b5c48ea2e27")
                        },
                        new
                        {
                            CityId = new Guid("3f36f6bf-cc28-44f9-a8da-9b2616b3f367"),
                            Disabled = false,
                            Name = "Pereira",
                            ProvinceId = new Guid("7268d451-86a4-49e0-9720-aae1df9d3381")
                        },
                        new
                        {
                            CityId = new Guid("b92b434c-ff14-426d-b099-49d1b4a098b2"),
                            Disabled = false,
                            Name = "Dosquebradas",
                            ProvinceId = new Guid("7268d451-86a4-49e0-9720-aae1df9d3381")
                        },
                        new
                        {
                            CityId = new Guid("0800e16d-ff09-4262-9956-68131fc99774"),
                            Disabled = false,
                            Name = "Santa Rosa de Cabal",
                            ProvinceId = new Guid("7268d451-86a4-49e0-9720-aae1df9d3381")
                        },
                        new
                        {
                            CityId = new Guid("eaf55909-be22-403e-a544-1a429700d690"),
                            Disabled = false,
                            Name = "San Andrés",
                            ProvinceId = new Guid("04fd8da1-4697-40d1-8c36-e19dbec98562")
                        },
                        new
                        {
                            CityId = new Guid("bf17ce66-76df-40f3-b4a4-ab156f60485d"),
                            Disabled = false,
                            Name = "Providencia",
                            ProvinceId = new Guid("04fd8da1-4697-40d1-8c36-e19dbec98562")
                        },
                        new
                        {
                            CityId = new Guid("6fde4c3d-ce52-44f1-be2b-24eb4b9c8685"),
                            Disabled = false,
                            Name = "Santa Catalina",
                            ProvinceId = new Guid("04fd8da1-4697-40d1-8c36-e19dbec98562")
                        },
                        new
                        {
                            CityId = new Guid("d42352e0-9ddc-4d30-9467-4420dcfc22d9"),
                            Disabled = false,
                            Name = "Bucaramanga",
                            ProvinceId = new Guid("a5cc110a-3f46-448f-a09e-388b10c0dc7a")
                        },
                        new
                        {
                            CityId = new Guid("7b073ff5-d9c6-404b-9262-e1b57db51fc8"),
                            Disabled = false,
                            Name = "Barrancabermeja",
                            ProvinceId = new Guid("a5cc110a-3f46-448f-a09e-388b10c0dc7a")
                        },
                        new
                        {
                            CityId = new Guid("c168b859-799b-461a-b66f-63022df56688"),
                            Disabled = false,
                            Name = "Piedecuesta",
                            ProvinceId = new Guid("a5cc110a-3f46-448f-a09e-388b10c0dc7a")
                        },
                        new
                        {
                            CityId = new Guid("704c67f5-47c7-404e-820a-3a02a111bb54"),
                            Disabled = false,
                            Name = "Sincelejo",
                            ProvinceId = new Guid("099bdbd0-b33f-420b-9a47-7d1981d3b0ea")
                        },
                        new
                        {
                            CityId = new Guid("493f526e-e568-42af-a65f-2b7ffe02c944"),
                            Disabled = false,
                            Name = "Corozal",
                            ProvinceId = new Guid("099bdbd0-b33f-420b-9a47-7d1981d3b0ea")
                        },
                        new
                        {
                            CityId = new Guid("5173b5a4-208b-4921-9135-ed7350049f4a"),
                            Disabled = false,
                            Name = "Montería",
                            ProvinceId = new Guid("099bdbd0-b33f-420b-9a47-7d1981d3b0ea")
                        },
                        new
                        {
                            CityId = new Guid("95399b79-1283-4a04-ba1a-dc18ae82e8d7"),
                            Disabled = false,
                            Name = "Ibagué",
                            ProvinceId = new Guid("c3b369e5-3eaf-4fdb-8645-ebe737af0a1f")
                        },
                        new
                        {
                            CityId = new Guid("3b6e69fa-f45a-4cc7-b67a-326f8849d162"),
                            Disabled = false,
                            Name = "Honda",
                            ProvinceId = new Guid("c3b369e5-3eaf-4fdb-8645-ebe737af0a1f")
                        },
                        new
                        {
                            CityId = new Guid("5dc9907a-36c5-4e82-abd9-505bdfdb340d"),
                            Disabled = false,
                            Name = "Armero Guayabal",
                            ProvinceId = new Guid("c3b369e5-3eaf-4fdb-8645-ebe737af0a1f")
                        },
                        new
                        {
                            CityId = new Guid("f88bf612-fcbb-4cc8-913d-8c6dd7c5bdd1"),
                            Disabled = false,
                            Name = "Cali",
                            ProvinceId = new Guid("70e699cd-d61b-4442-8dbe-975ac58b5f6a")
                        },
                        new
                        {
                            CityId = new Guid("6b232557-c332-4b64-b29d-3f870495047e"),
                            Disabled = false,
                            Name = "Palmira",
                            ProvinceId = new Guid("70e699cd-d61b-4442-8dbe-975ac58b5f6a")
                        },
                        new
                        {
                            CityId = new Guid("ed328c11-41f8-43d2-872f-7267e3f118ff"),
                            Disabled = false,
                            Name = "Buenaventura",
                            ProvinceId = new Guid("70e699cd-d61b-4442-8dbe-975ac58b5f6a")
                        },
                        new
                        {
                            CityId = new Guid("81b7f7b0-bb96-444c-8fb2-d021e7fdf820"),
                            Disabled = false,
                            Name = "Mitú",
                            ProvinceId = new Guid("d1884472-3261-4d4e-baa4-1e9ab16d7009")
                        },
                        new
                        {
                            CityId = new Guid("5b843414-f9f6-4ffd-8afb-d227af6d5d8b"),
                            Disabled = false,
                            Name = "Yavaraté",
                            ProvinceId = new Guid("d1884472-3261-4d4e-baa4-1e9ab16d7009")
                        },
                        new
                        {
                            CityId = new Guid("41229003-6040-43e4-b839-6c3443b3a8c1"),
                            Disabled = false,
                            Name = "Santa Rosalía",
                            ProvinceId = new Guid("d1884472-3261-4d4e-baa4-1e9ab16d7009")
                        },
                        new
                        {
                            CityId = new Guid("158dad12-ea5b-4ff4-b923-70219f582fcf"),
                            Disabled = false,
                            Name = "Puerto Carreño",
                            ProvinceId = new Guid("11abad68-b73f-48e3-a8ea-3061cf443638")
                        },
                        new
                        {
                            CityId = new Guid("7f778bc0-0cf2-4b1e-93cf-7103d0ca6760"),
                            Disabled = false,
                            Name = "La Primavera",
                            ProvinceId = new Guid("11abad68-b73f-48e3-a8ea-3061cf443638")
                        },
                        new
                        {
                            CityId = new Guid("64e42a67-a0bc-4c6f-85a3-662c038eea4b"),
                            Disabled = false,
                            Name = "Santa Helena",
                            ProvinceId = new Guid("11abad68-b73f-48e3-a8ea-3061cf443638")
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CountryModel", b =>
                {
                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ctr_country_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("ctr_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctr_name");

                    b.HasKey("CountryId");

                    b.ToTable("tbl_country");

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Colombia"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("prv_province_id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ctr_country_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("prv_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prv_name");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.ToTable("tbl_province");

                    b.HasData(
                        new
                        {
                            ProvinceId = new Guid("ce5e384b-aba3-419f-b44a-838d14fef4d4"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Amazonas"
                        },
                        new
                        {
                            ProvinceId = new Guid("f54ef90c-652d-4b02-84bd-a59922663c0d"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Antioquia"
                        },
                        new
                        {
                            ProvinceId = new Guid("e9a5d171-872f-433a-b2f8-387d4bd0f7da"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Arauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("ccd1f1e8-5362-47f3-b756-45638205937e"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Atlántico"
                        },
                        new
                        {
                            ProvinceId = new Guid("1bd8ee39-acfc-4698-af69-50482e771bf8"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Bolívar"
                        },
                        new
                        {
                            ProvinceId = new Guid("f04849cf-b20f-4b68-ba5c-d530860e877a"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Boyacá"
                        },
                        new
                        {
                            ProvinceId = new Guid("fe6f20de-70e1-4e93-8bf9-1a7a9c52b4e3"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Caldas"
                        },
                        new
                        {
                            ProvinceId = new Guid("389cc7dd-b657-47cf-91d9-03bb7a07a387"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Caquetá"
                        },
                        new
                        {
                            ProvinceId = new Guid("ddc81f77-5305-40c9-af13-c79f5b11651f"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Casanare"
                        },
                        new
                        {
                            ProvinceId = new Guid("d58ad120-0875-471b-a094-9bf4f9614501"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Cauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("8899a64c-cb80-4e17-ae51-6138202c80b1"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Cesar"
                        },
                        new
                        {
                            ProvinceId = new Guid("20703693-f1e1-47df-aced-f2fb026121f0"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Chocó"
                        },
                        new
                        {
                            ProvinceId = new Guid("881810ca-5d93-4a0a-adb6-1938069d7b83"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Córdoba"
                        },
                        new
                        {
                            ProvinceId = new Guid("58989ded-a4de-4b43-a8af-3edcc83a3a93"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Cundinamarca"
                        },
                        new
                        {
                            ProvinceId = new Guid("9130e757-5e7d-4a02-9177-3740c9d9a1d8"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Guainía"
                        },
                        new
                        {
                            ProvinceId = new Guid("1b489446-0ac4-466f-ad8b-33401107e38e"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Guaviare"
                        },
                        new
                        {
                            ProvinceId = new Guid("d5903001-75aa-4019-b730-77d39df3bc9f"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Huila"
                        },
                        new
                        {
                            ProvinceId = new Guid("c51dbd19-e282-478e-bd00-5c0fe649f22c"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "La Guajira"
                        },
                        new
                        {
                            ProvinceId = new Guid("f0abb4fa-14a1-4029-93e4-378bd229e68f"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Magdalena"
                        },
                        new
                        {
                            ProvinceId = new Guid("786717f0-a4a6-4610-bf16-8b602f868a66"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Meta"
                        },
                        new
                        {
                            ProvinceId = new Guid("5e1af82f-834e-4caa-bfb7-cd92d08c92d6"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Nariño"
                        },
                        new
                        {
                            ProvinceId = new Guid("ccda11b3-cbfc-4039-bf79-8a45e0bd6a3d"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Norte de Santander"
                        },
                        new
                        {
                            ProvinceId = new Guid("090758f1-8666-4bb5-89f0-db8e154cee56"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Putumayo"
                        },
                        new
                        {
                            ProvinceId = new Guid("b7f674a8-94fe-4ec1-8611-1b5c48ea2e27"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Quindío"
                        },
                        new
                        {
                            ProvinceId = new Guid("7268d451-86a4-49e0-9720-aae1df9d3381"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Risaralda"
                        },
                        new
                        {
                            ProvinceId = new Guid("04fd8da1-4697-40d1-8c36-e19dbec98562"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "San Andrés y Providencia"
                        },
                        new
                        {
                            ProvinceId = new Guid("a5cc110a-3f46-448f-a09e-388b10c0dc7a"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Santander"
                        },
                        new
                        {
                            ProvinceId = new Guid("099bdbd0-b33f-420b-9a47-7d1981d3b0ea"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Sucre"
                        },
                        new
                        {
                            ProvinceId = new Guid("c3b369e5-3eaf-4fdb-8645-ebe737af0a1f"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Tolima"
                        },
                        new
                        {
                            ProvinceId = new Guid("70e699cd-d61b-4442-8dbe-975ac58b5f6a"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Valle del Cauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("d1884472-3261-4d4e-baa4-1e9ab16d7009"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Vaupés"
                        },
                        new
                        {
                            ProvinceId = new Guid("11abad68-b73f-48e3-a8ea-3061cf443638"),
                            CountryId = new Guid("39a4f539-8bf5-4fbc-8db8-b09c1d75146f"),
                            Disabled = false,
                            Name = "Vichada"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CityModel", b =>
                {
                    b.HasOne("Profiles.Infrastructure.Persistence.Models.ProvinceModel", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.HasOne("Profiles.Infrastructure.Persistence.Models.CountryModel", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CountryModel", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
