// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Profiles.Infrastructure.Persistence;

#nullable disable

namespace Profiles.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CityModel", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("cty_city_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("cty_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cty_name");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("prv_province_id");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("tbl_city");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("256b34a1-7be3-4a7b-a697-c6e0452c64e5"),
                            Disabled = false,
                            Name = "Leticia",
                            ProvinceId = new Guid("bfcef0ed-07ae-4112-817b-607d6cca6183")
                        },
                        new
                        {
                            CityId = new Guid("fc1611f1-e33b-4b77-8cf9-caac151298f6"),
                            Disabled = false,
                            Name = "Medellín",
                            ProvinceId = new Guid("829f4bbf-b228-4311-a6f0-ff16246532a0")
                        },
                        new
                        {
                            CityId = new Guid("38963ebf-daa5-4793-89b4-b7f30710dd55"),
                            Disabled = false,
                            Name = "Apartadó",
                            ProvinceId = new Guid("829f4bbf-b228-4311-a6f0-ff16246532a0")
                        },
                        new
                        {
                            CityId = new Guid("cd06cc7f-c7a8-4d43-92d2-8be1b435bede"),
                            Disabled = false,
                            Name = "Turbo",
                            ProvinceId = new Guid("829f4bbf-b228-4311-a6f0-ff16246532a0")
                        },
                        new
                        {
                            CityId = new Guid("3c1e5660-cb61-4d73-ae1a-8ef6045b5696"),
                            Disabled = false,
                            Name = "Arauca",
                            ProvinceId = new Guid("bf291904-29a3-4dc4-9e17-2e16ddb791cd")
                        },
                        new
                        {
                            CityId = new Guid("9bb5235c-1888-4fd4-9386-ed5467c7833c"),
                            Disabled = false,
                            Name = "Saravena",
                            ProvinceId = new Guid("bf291904-29a3-4dc4-9e17-2e16ddb791cd")
                        },
                        new
                        {
                            CityId = new Guid("be86b1c7-99a8-48a6-bb41-d83d3be45809"),
                            Disabled = false,
                            Name = "Fortul",
                            ProvinceId = new Guid("bf291904-29a3-4dc4-9e17-2e16ddb791cd")
                        },
                        new
                        {
                            CityId = new Guid("0a1bd930-6d14-4a3d-9448-f5bc59c4c69e"),
                            Disabled = false,
                            Name = "Barranquilla",
                            ProvinceId = new Guid("2eb11cff-f444-4441-ac74-4138ae3ab71d")
                        },
                        new
                        {
                            CityId = new Guid("b7cb49a0-cc41-41f1-be4a-f979ba43b07f"),
                            Disabled = false,
                            Name = "Soledad",
                            ProvinceId = new Guid("2eb11cff-f444-4441-ac74-4138ae3ab71d")
                        },
                        new
                        {
                            CityId = new Guid("d400a851-c8a6-4fca-9ef9-bd77336f148f"),
                            Disabled = false,
                            Name = "Puerto Colombia",
                            ProvinceId = new Guid("2eb11cff-f444-4441-ac74-4138ae3ab71d")
                        },
                        new
                        {
                            CityId = new Guid("e1c2757a-8328-4b40-88a3-8e0ce94520c5"),
                            Disabled = false,
                            Name = "Cartagena de Indias",
                            ProvinceId = new Guid("a083ee70-5155-4bec-8918-9eb21a51d99a")
                        },
                        new
                        {
                            CityId = new Guid("724fb9bf-1add-4a1e-8f80-d789cad8f3e9"),
                            Disabled = false,
                            Name = "Magangué",
                            ProvinceId = new Guid("a083ee70-5155-4bec-8918-9eb21a51d99a")
                        },
                        new
                        {
                            CityId = new Guid("57a3da02-28cb-4f17-98ed-d8a6192c2d78"),
                            Disabled = false,
                            Name = "Cartagena del Chairá",
                            ProvinceId = new Guid("a083ee70-5155-4bec-8918-9eb21a51d99a")
                        },
                        new
                        {
                            CityId = new Guid("756d57eb-8284-40eb-8532-0378012a664f"),
                            Disabled = false,
                            Name = "Tunja",
                            ProvinceId = new Guid("94a81beb-d8fa-4f14-a7fd-a5050871da23")
                        },
                        new
                        {
                            CityId = new Guid("a9e3e91e-a27b-4bae-a191-46f8dabb733e"),
                            Disabled = false,
                            Name = "Sogamoso",
                            ProvinceId = new Guid("94a81beb-d8fa-4f14-a7fd-a5050871da23")
                        },
                        new
                        {
                            CityId = new Guid("91ebd240-6cb0-4b1c-9ae6-1ee4e0c2e7fa"),
                            Disabled = false,
                            Name = "Duitama",
                            ProvinceId = new Guid("94a81beb-d8fa-4f14-a7fd-a5050871da23")
                        },
                        new
                        {
                            CityId = new Guid("363347e4-568d-4ab0-b809-473af5f4eb6d"),
                            Disabled = false,
                            Name = "Manizales",
                            ProvinceId = new Guid("0710872a-2b6e-4f75-a115-18db523a42f3")
                        },
                        new
                        {
                            CityId = new Guid("a388515e-2821-4316-9e75-666665b92858"),
                            Disabled = false,
                            Name = "Pereira",
                            ProvinceId = new Guid("0710872a-2b6e-4f75-a115-18db523a42f3")
                        },
                        new
                        {
                            CityId = new Guid("791f61c8-8eb0-4810-a164-1920bdbce4bc"),
                            Disabled = false,
                            Name = "Chinchiná",
                            ProvinceId = new Guid("0710872a-2b6e-4f75-a115-18db523a42f3")
                        },
                        new
                        {
                            CityId = new Guid("32c9e257-f30c-47f3-8f1b-fb5199d48b3a"),
                            Disabled = false,
                            Name = "Florencia",
                            ProvinceId = new Guid("8669ba3a-8948-45ee-80a2-4da1986a3498")
                        },
                        new
                        {
                            CityId = new Guid("12c2c0db-f3dc-4f46-a2e7-036b82190762"),
                            Disabled = false,
                            Name = "Cartagena del Chairá",
                            ProvinceId = new Guid("8669ba3a-8948-45ee-80a2-4da1986a3498")
                        },
                        new
                        {
                            CityId = new Guid("f0c6829c-a3a9-4223-89c7-9820f16d48ee"),
                            Disabled = false,
                            Name = "Morelia",
                            ProvinceId = new Guid("8669ba3a-8948-45ee-80a2-4da1986a3498")
                        },
                        new
                        {
                            CityId = new Guid("16a01522-7a9e-4a0c-a783-d092750ede32"),
                            Disabled = false,
                            Name = "Yopal",
                            ProvinceId = new Guid("8a152795-49c0-408a-a359-e9ce79d3af66")
                        },
                        new
                        {
                            CityId = new Guid("da1f4d8c-a12a-4a8d-b09d-e773363ba6e3"),
                            Disabled = false,
                            Name = "Aguazul",
                            ProvinceId = new Guid("8a152795-49c0-408a-a359-e9ce79d3af66")
                        },
                        new
                        {
                            CityId = new Guid("fddf0b25-bad6-4a4d-97a1-1ded9a1598a1"),
                            Disabled = false,
                            Name = "Tauramena",
                            ProvinceId = new Guid("8a152795-49c0-408a-a359-e9ce79d3af66")
                        },
                        new
                        {
                            CityId = new Guid("e95c1f1c-c873-4dd1-8325-85d5771e1b39"),
                            Disabled = false,
                            Name = "Popayán",
                            ProvinceId = new Guid("ae663cc5-9db8-47b3-b326-3c874feea4d1")
                        },
                        new
                        {
                            CityId = new Guid("ebb6d771-eb21-4a05-8b37-03c5746ef38b"),
                            Disabled = false,
                            Name = "Silvia",
                            ProvinceId = new Guid("ae663cc5-9db8-47b3-b326-3c874feea4d1")
                        },
                        new
                        {
                            CityId = new Guid("c98cc646-fb83-40cb-8aa7-2810308dffcf"),
                            Disabled = false,
                            Name = "Santander de Quilichao",
                            ProvinceId = new Guid("ae663cc5-9db8-47b3-b326-3c874feea4d1")
                        },
                        new
                        {
                            CityId = new Guid("4f99f030-9649-47a2-8ad8-5a4b5a7d7260"),
                            Disabled = false,
                            Name = "Valledupar",
                            ProvinceId = new Guid("843c2372-735b-482f-b3fa-1db3d9305d01")
                        },
                        new
                        {
                            CityId = new Guid("a88130f5-2de5-4524-b608-006ade4fd5c6"),
                            Disabled = false,
                            Name = "Aguachica",
                            ProvinceId = new Guid("843c2372-735b-482f-b3fa-1db3d9305d01")
                        },
                        new
                        {
                            CityId = new Guid("e12bdca9-b19a-4214-a47c-2ecbd54210de"),
                            Disabled = false,
                            Name = "La Paz",
                            ProvinceId = new Guid("843c2372-735b-482f-b3fa-1db3d9305d01")
                        },
                        new
                        {
                            CityId = new Guid("ec47b3ec-649b-43a2-bc50-7c9fca486247"),
                            Disabled = false,
                            Name = "Quibdó",
                            ProvinceId = new Guid("7a532de2-b198-4f98-b899-321e1c666be0")
                        },
                        new
                        {
                            CityId = new Guid("21370b7b-ec72-4a61-b340-af12908f61bf"),
                            Disabled = false,
                            Name = "Istmina",
                            ProvinceId = new Guid("7a532de2-b198-4f98-b899-321e1c666be0")
                        },
                        new
                        {
                            CityId = new Guid("10d914dd-82f9-401d-b773-449de88f15b9"),
                            Disabled = false,
                            Name = "Novita",
                            ProvinceId = new Guid("7a532de2-b198-4f98-b899-321e1c666be0")
                        },
                        new
                        {
                            CityId = new Guid("0a1aad59-f251-41f3-8700-75577de21dd9"),
                            Disabled = false,
                            Name = "Montería",
                            ProvinceId = new Guid("8d1e8fc1-8219-45d8-9e96-9d87f74effd0")
                        },
                        new
                        {
                            CityId = new Guid("a6982a2b-9b20-4b53-9ef4-4561e0c37a16"),
                            Disabled = false,
                            Name = "Cereté",
                            ProvinceId = new Guid("8d1e8fc1-8219-45d8-9e96-9d87f74effd0")
                        },
                        new
                        {
                            CityId = new Guid("edd6c842-1597-4abe-ba12-3940f919821e"),
                            Disabled = false,
                            Name = "Lorica",
                            ProvinceId = new Guid("8d1e8fc1-8219-45d8-9e96-9d87f74effd0")
                        },
                        new
                        {
                            CityId = new Guid("9340d9a2-1c17-4e36-8f52-1edb9b1d1caf"),
                            Disabled = false,
                            Name = "Bogotá",
                            ProvinceId = new Guid("962258d4-f027-42b7-8e13-18e6997ab0db")
                        },
                        new
                        {
                            CityId = new Guid("ae88b544-2640-47aa-9f6f-2ccb9c887412"),
                            Disabled = false,
                            Name = "Soacha",
                            ProvinceId = new Guid("962258d4-f027-42b7-8e13-18e6997ab0db")
                        },
                        new
                        {
                            CityId = new Guid("0dfa4803-4804-44fc-8e9b-0ef02a51552d"),
                            Disabled = false,
                            Name = "Zipaquirá",
                            ProvinceId = new Guid("962258d4-f027-42b7-8e13-18e6997ab0db")
                        },
                        new
                        {
                            CityId = new Guid("14f8e95a-ee0e-49bd-bece-40bb677349c8"),
                            Disabled = false,
                            Name = "Inírida",
                            ProvinceId = new Guid("000d3c20-51ab-4f2c-8e5e-7fed465349ed")
                        },
                        new
                        {
                            CityId = new Guid("76787dc4-3e2b-4f4f-9573-df780c4b0bcb"),
                            Disabled = false,
                            Name = "Puerto Inírida",
                            ProvinceId = new Guid("000d3c20-51ab-4f2c-8e5e-7fed465349ed")
                        },
                        new
                        {
                            CityId = new Guid("2031264f-4f89-4d62-ac45-2f764099ec3d"),
                            Disabled = false,
                            Name = "Memarí",
                            ProvinceId = new Guid("000d3c20-51ab-4f2c-8e5e-7fed465349ed")
                        },
                        new
                        {
                            CityId = new Guid("bc88fd6a-958f-49ed-9e74-27f849449abd"),
                            Disabled = false,
                            Name = "San José del Guaviare",
                            ProvinceId = new Guid("b7e67c76-e4de-4c59-88b4-144c37dadc11")
                        },
                        new
                        {
                            CityId = new Guid("fe94d913-065e-4ba5-9834-7807a07c5096"),
                            Disabled = false,
                            Name = "Calamar",
                            ProvinceId = new Guid("b7e67c76-e4de-4c59-88b4-144c37dadc11")
                        },
                        new
                        {
                            CityId = new Guid("cb6cd0e4-5714-4ad9-9df4-e16e37ee7ac5"),
                            Disabled = false,
                            Name = "El Retén",
                            ProvinceId = new Guid("b7e67c76-e4de-4c59-88b4-144c37dadc11")
                        },
                        new
                        {
                            CityId = new Guid("1659c5ee-ca51-4cc6-ac42-10640a988491"),
                            Disabled = false,
                            Name = "Neiva",
                            ProvinceId = new Guid("32c10d0d-4b2f-4708-b386-b306fe281429")
                        },
                        new
                        {
                            CityId = new Guid("4596ac63-8a5c-43f9-82ae-39f41a0e8c40"),
                            Disabled = false,
                            Name = "Garzón",
                            ProvinceId = new Guid("32c10d0d-4b2f-4708-b386-b306fe281429")
                        },
                        new
                        {
                            CityId = new Guid("18919f38-0257-4320-a217-0e29433c227e"),
                            Disabled = false,
                            Name = "Pitalito",
                            ProvinceId = new Guid("32c10d0d-4b2f-4708-b386-b306fe281429")
                        },
                        new
                        {
                            CityId = new Guid("f1a7c563-ae62-4977-a464-0286a4d75dc5"),
                            Disabled = false,
                            Name = "Riohacha",
                            ProvinceId = new Guid("26f987d9-af02-4215-8e04-7c044973cb3c")
                        },
                        new
                        {
                            CityId = new Guid("230f841a-e2cf-4064-9894-0d095898bb27"),
                            Disabled = false,
                            Name = "Maicao",
                            ProvinceId = new Guid("26f987d9-af02-4215-8e04-7c044973cb3c")
                        },
                        new
                        {
                            CityId = new Guid("d22614d6-cb2f-4e02-8400-9782c759297b"),
                            Disabled = false,
                            Name = "Uribia",
                            ProvinceId = new Guid("26f987d9-af02-4215-8e04-7c044973cb3c")
                        },
                        new
                        {
                            CityId = new Guid("380aa3e0-d086-47bd-a206-ad7ca70e81dd"),
                            Disabled = false,
                            Name = "Santa Marta",
                            ProvinceId = new Guid("9fda204e-6ad8-4282-9fdd-d58853910641")
                        },
                        new
                        {
                            CityId = new Guid("f8a6d7e6-27e8-4f24-b33d-9efb2fb4c4fe"),
                            Disabled = false,
                            Name = "Aracataca",
                            ProvinceId = new Guid("9fda204e-6ad8-4282-9fdd-d58853910641")
                        },
                        new
                        {
                            CityId = new Guid("dcde8c23-3eea-40fa-a3bc-94a4a7f5608b"),
                            Disabled = false,
                            Name = "Ciénaga",
                            ProvinceId = new Guid("9fda204e-6ad8-4282-9fdd-d58853910641")
                        },
                        new
                        {
                            CityId = new Guid("653b739d-47c7-4d26-ab7a-c4bf120d3f00"),
                            Disabled = false,
                            Name = "Villavicencio",
                            ProvinceId = new Guid("9a6f0465-07f8-4b2b-b5a0-88c68bde8d68")
                        },
                        new
                        {
                            CityId = new Guid("d5317b09-8c06-4ec7-b01a-17181753cc03"),
                            Disabled = false,
                            Name = "Acacias",
                            ProvinceId = new Guid("9a6f0465-07f8-4b2b-b5a0-88c68bde8d68")
                        },
                        new
                        {
                            CityId = new Guid("4f09ef3d-e530-4079-a1dc-d6730ca45f10"),
                            Disabled = false,
                            Name = "Granada",
                            ProvinceId = new Guid("9a6f0465-07f8-4b2b-b5a0-88c68bde8d68")
                        },
                        new
                        {
                            CityId = new Guid("0954f045-13c4-4d9e-9dc0-b8b01f882516"),
                            Disabled = false,
                            Name = "San Juan de Pasto",
                            ProvinceId = new Guid("52ae67a3-6d32-477c-91b9-7069f544038f")
                        },
                        new
                        {
                            CityId = new Guid("e243acd8-c291-4b6b-91a0-0c52b2974009"),
                            Disabled = false,
                            Name = "Tumaco",
                            ProvinceId = new Guid("52ae67a3-6d32-477c-91b9-7069f544038f")
                        },
                        new
                        {
                            CityId = new Guid("c8b39358-8e87-460e-926b-6f2745c1d5f0"),
                            Disabled = false,
                            Name = "Ipiales",
                            ProvinceId = new Guid("52ae67a3-6d32-477c-91b9-7069f544038f")
                        },
                        new
                        {
                            CityId = new Guid("a32e321c-196e-4f4c-bd44-166e1296adf6"),
                            Disabled = false,
                            Name = "Cúcuta",
                            ProvinceId = new Guid("c457fc53-07c2-45e4-be76-88e8ed62f192")
                        },
                        new
                        {
                            CityId = new Guid("46aa479a-c974-4c1e-994d-f9736fd96c22"),
                            Disabled = false,
                            Name = "Ocaña",
                            ProvinceId = new Guid("c457fc53-07c2-45e4-be76-88e8ed62f192")
                        },
                        new
                        {
                            CityId = new Guid("3d5f3475-b6e4-42fe-a62d-c81788d00dfc"),
                            Disabled = false,
                            Name = "Pamplona",
                            ProvinceId = new Guid("c457fc53-07c2-45e4-be76-88e8ed62f192")
                        },
                        new
                        {
                            CityId = new Guid("e9c02421-160a-448e-b8b0-57eb5d9d59ea"),
                            Disabled = false,
                            Name = "Mocoa",
                            ProvinceId = new Guid("a5654338-8151-497b-847e-ca674269a8ae")
                        },
                        new
                        {
                            CityId = new Guid("c35d923f-cf84-4c52-b6c1-f035f1709867"),
                            Disabled = false,
                            Name = "Puerto Asís",
                            ProvinceId = new Guid("a5654338-8151-497b-847e-ca674269a8ae")
                        },
                        new
                        {
                            CityId = new Guid("66940d4d-47ae-4dff-bf46-9a882edcdc46"),
                            Disabled = false,
                            Name = "Orito",
                            ProvinceId = new Guid("a5654338-8151-497b-847e-ca674269a8ae")
                        },
                        new
                        {
                            CityId = new Guid("0bad1089-f9fe-4494-93fd-aa2e4fb62f28"),
                            Disabled = false,
                            Name = "Armenia",
                            ProvinceId = new Guid("15132b31-b888-47a5-abfb-22765d976e54")
                        },
                        new
                        {
                            CityId = new Guid("ba55d887-f4ea-4447-a7a5-f96abb1546c5"),
                            Disabled = false,
                            Name = "Calarcá",
                            ProvinceId = new Guid("15132b31-b888-47a5-abfb-22765d976e54")
                        },
                        new
                        {
                            CityId = new Guid("ff554b14-76eb-4ed6-9b03-2cd1897288f1"),
                            Disabled = false,
                            Name = "La Tebaida",
                            ProvinceId = new Guid("15132b31-b888-47a5-abfb-22765d976e54")
                        },
                        new
                        {
                            CityId = new Guid("5db3629a-fe7c-455f-8e55-de545665e6ba"),
                            Disabled = false,
                            Name = "Pereira",
                            ProvinceId = new Guid("272261ca-42de-4d75-a80f-b1fe0763df76")
                        },
                        new
                        {
                            CityId = new Guid("c8d8b061-fc13-4c78-9c27-968018e58d45"),
                            Disabled = false,
                            Name = "Dosquebradas",
                            ProvinceId = new Guid("272261ca-42de-4d75-a80f-b1fe0763df76")
                        },
                        new
                        {
                            CityId = new Guid("1799f51f-18cf-44fb-95ec-9dc40f292913"),
                            Disabled = false,
                            Name = "Santa Rosa de Cabal",
                            ProvinceId = new Guid("272261ca-42de-4d75-a80f-b1fe0763df76")
                        },
                        new
                        {
                            CityId = new Guid("80050ff5-3e28-471e-8077-0b3ced19b5f8"),
                            Disabled = false,
                            Name = "San Andrés",
                            ProvinceId = new Guid("24d43b52-5c8b-4321-a062-d7a97a1c280a")
                        },
                        new
                        {
                            CityId = new Guid("5044bc5d-3940-4699-955a-1668f0d9b3c4"),
                            Disabled = false,
                            Name = "Providencia",
                            ProvinceId = new Guid("24d43b52-5c8b-4321-a062-d7a97a1c280a")
                        },
                        new
                        {
                            CityId = new Guid("0ebc3ea4-d656-4732-aee3-dfe90b8f4720"),
                            Disabled = false,
                            Name = "Santa Catalina",
                            ProvinceId = new Guid("24d43b52-5c8b-4321-a062-d7a97a1c280a")
                        },
                        new
                        {
                            CityId = new Guid("dd7cda2e-8bac-400d-b363-7f9dd50b6567"),
                            Disabled = false,
                            Name = "Bucaramanga",
                            ProvinceId = new Guid("161c7888-230e-49c0-9a9e-2852507069db")
                        },
                        new
                        {
                            CityId = new Guid("0e4963c0-5e8e-497f-97e9-796cb807b62c"),
                            Disabled = false,
                            Name = "Barrancabermeja",
                            ProvinceId = new Guid("161c7888-230e-49c0-9a9e-2852507069db")
                        },
                        new
                        {
                            CityId = new Guid("1321dd1c-d8af-4fee-a70b-fb93d8222108"),
                            Disabled = false,
                            Name = "Piedecuesta",
                            ProvinceId = new Guid("161c7888-230e-49c0-9a9e-2852507069db")
                        },
                        new
                        {
                            CityId = new Guid("1c9323a4-8a51-45fd-ae30-8063e2abbd48"),
                            Disabled = false,
                            Name = "Sincelejo",
                            ProvinceId = new Guid("b631a60a-11eb-4b2f-a25d-44374558cd3c")
                        },
                        new
                        {
                            CityId = new Guid("3f26f03b-ddef-4645-8e8f-14f94420b91b"),
                            Disabled = false,
                            Name = "Corozal",
                            ProvinceId = new Guid("b631a60a-11eb-4b2f-a25d-44374558cd3c")
                        },
                        new
                        {
                            CityId = new Guid("63053a1a-fe00-4497-b1b9-994abceb976b"),
                            Disabled = false,
                            Name = "Montería",
                            ProvinceId = new Guid("b631a60a-11eb-4b2f-a25d-44374558cd3c")
                        },
                        new
                        {
                            CityId = new Guid("f82a24f4-fc95-45b7-9223-25953c36d16b"),
                            Disabled = false,
                            Name = "Ibagué",
                            ProvinceId = new Guid("f23cad77-59f9-443f-a5a3-28812c9ba761")
                        },
                        new
                        {
                            CityId = new Guid("2e1768f8-3070-4be9-b2f1-e58cf1daa11a"),
                            Disabled = false,
                            Name = "Honda",
                            ProvinceId = new Guid("f23cad77-59f9-443f-a5a3-28812c9ba761")
                        },
                        new
                        {
                            CityId = new Guid("c5944a51-0948-4164-a303-5455f698ee59"),
                            Disabled = false,
                            Name = "Armero Guayabal",
                            ProvinceId = new Guid("f23cad77-59f9-443f-a5a3-28812c9ba761")
                        },
                        new
                        {
                            CityId = new Guid("b914186d-89a2-462b-9448-c6daab2113e5"),
                            Disabled = false,
                            Name = "Cali",
                            ProvinceId = new Guid("de2567c7-c332-45e5-81a7-449d2f753a3b")
                        },
                        new
                        {
                            CityId = new Guid("2e25cd86-1b77-464c-8ed8-0c1317a57cbd"),
                            Disabled = false,
                            Name = "Palmira",
                            ProvinceId = new Guid("de2567c7-c332-45e5-81a7-449d2f753a3b")
                        },
                        new
                        {
                            CityId = new Guid("ade00c92-e3bb-43c1-9ca6-fc840b600542"),
                            Disabled = false,
                            Name = "Buenaventura",
                            ProvinceId = new Guid("de2567c7-c332-45e5-81a7-449d2f753a3b")
                        },
                        new
                        {
                            CityId = new Guid("904390c6-c73b-430c-8217-303eea9b794d"),
                            Disabled = false,
                            Name = "Mitú",
                            ProvinceId = new Guid("e6f24a6f-f852-4c5d-8d5e-4dc03e5a4214")
                        },
                        new
                        {
                            CityId = new Guid("c1ac629f-ad47-4ca7-9551-3b272e7fc302"),
                            Disabled = false,
                            Name = "Yavaraté",
                            ProvinceId = new Guid("e6f24a6f-f852-4c5d-8d5e-4dc03e5a4214")
                        },
                        new
                        {
                            CityId = new Guid("2433dde4-8a3c-4490-8996-68685bfe2290"),
                            Disabled = false,
                            Name = "Santa Rosalía",
                            ProvinceId = new Guid("e6f24a6f-f852-4c5d-8d5e-4dc03e5a4214")
                        },
                        new
                        {
                            CityId = new Guid("afbc444d-1b5c-4289-8471-a4eb01b9c7ed"),
                            Disabled = false,
                            Name = "Puerto Carreño",
                            ProvinceId = new Guid("daaff97f-5979-43f0-ae0b-8e5a7d44fa17")
                        },
                        new
                        {
                            CityId = new Guid("7bc89b21-d5fd-4bbe-868b-78b4e14602d9"),
                            Disabled = false,
                            Name = "La Primavera",
                            ProvinceId = new Guid("daaff97f-5979-43f0-ae0b-8e5a7d44fa17")
                        },
                        new
                        {
                            CityId = new Guid("022a899d-023c-4489-8fae-2bb8210c597b"),
                            Disabled = false,
                            Name = "Santa Helena",
                            ProvinceId = new Guid("daaff97f-5979-43f0-ae0b-8e5a7d44fa17")
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CountryModel", b =>
                {
                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ctr_country_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("ctr_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctr_name");

                    b.HasKey("CountryId");

                    b.ToTable("tbl_country");

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Colombia"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("prv_province_id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("ctr_country_id");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("prv_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prv_name");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.ToTable("tbl_province");

                    b.HasData(
                        new
                        {
                            ProvinceId = new Guid("bfcef0ed-07ae-4112-817b-607d6cca6183"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Amazonas"
                        },
                        new
                        {
                            ProvinceId = new Guid("829f4bbf-b228-4311-a6f0-ff16246532a0"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Antioquia"
                        },
                        new
                        {
                            ProvinceId = new Guid("bf291904-29a3-4dc4-9e17-2e16ddb791cd"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Arauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("2eb11cff-f444-4441-ac74-4138ae3ab71d"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Atlántico"
                        },
                        new
                        {
                            ProvinceId = new Guid("a083ee70-5155-4bec-8918-9eb21a51d99a"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Bolívar"
                        },
                        new
                        {
                            ProvinceId = new Guid("94a81beb-d8fa-4f14-a7fd-a5050871da23"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Boyacá"
                        },
                        new
                        {
                            ProvinceId = new Guid("0710872a-2b6e-4f75-a115-18db523a42f3"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Caldas"
                        },
                        new
                        {
                            ProvinceId = new Guid("8669ba3a-8948-45ee-80a2-4da1986a3498"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Caquetá"
                        },
                        new
                        {
                            ProvinceId = new Guid("8a152795-49c0-408a-a359-e9ce79d3af66"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Casanare"
                        },
                        new
                        {
                            ProvinceId = new Guid("ae663cc5-9db8-47b3-b326-3c874feea4d1"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Cauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("843c2372-735b-482f-b3fa-1db3d9305d01"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Cesar"
                        },
                        new
                        {
                            ProvinceId = new Guid("7a532de2-b198-4f98-b899-321e1c666be0"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Chocó"
                        },
                        new
                        {
                            ProvinceId = new Guid("8d1e8fc1-8219-45d8-9e96-9d87f74effd0"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Córdoba"
                        },
                        new
                        {
                            ProvinceId = new Guid("962258d4-f027-42b7-8e13-18e6997ab0db"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Cundinamarca"
                        },
                        new
                        {
                            ProvinceId = new Guid("000d3c20-51ab-4f2c-8e5e-7fed465349ed"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Guainía"
                        },
                        new
                        {
                            ProvinceId = new Guid("b7e67c76-e4de-4c59-88b4-144c37dadc11"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Guaviare"
                        },
                        new
                        {
                            ProvinceId = new Guid("32c10d0d-4b2f-4708-b386-b306fe281429"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Huila"
                        },
                        new
                        {
                            ProvinceId = new Guid("26f987d9-af02-4215-8e04-7c044973cb3c"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "La Guajira"
                        },
                        new
                        {
                            ProvinceId = new Guid("9fda204e-6ad8-4282-9fdd-d58853910641"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Magdalena"
                        },
                        new
                        {
                            ProvinceId = new Guid("9a6f0465-07f8-4b2b-b5a0-88c68bde8d68"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Meta"
                        },
                        new
                        {
                            ProvinceId = new Guid("52ae67a3-6d32-477c-91b9-7069f544038f"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Nariño"
                        },
                        new
                        {
                            ProvinceId = new Guid("c457fc53-07c2-45e4-be76-88e8ed62f192"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Norte de Santander"
                        },
                        new
                        {
                            ProvinceId = new Guid("a5654338-8151-497b-847e-ca674269a8ae"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Putumayo"
                        },
                        new
                        {
                            ProvinceId = new Guid("15132b31-b888-47a5-abfb-22765d976e54"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Quindío"
                        },
                        new
                        {
                            ProvinceId = new Guid("272261ca-42de-4d75-a80f-b1fe0763df76"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Risaralda"
                        },
                        new
                        {
                            ProvinceId = new Guid("24d43b52-5c8b-4321-a062-d7a97a1c280a"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "San Andrés y Providencia"
                        },
                        new
                        {
                            ProvinceId = new Guid("161c7888-230e-49c0-9a9e-2852507069db"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Santander"
                        },
                        new
                        {
                            ProvinceId = new Guid("b631a60a-11eb-4b2f-a25d-44374558cd3c"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Sucre"
                        },
                        new
                        {
                            ProvinceId = new Guid("f23cad77-59f9-443f-a5a3-28812c9ba761"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Tolima"
                        },
                        new
                        {
                            ProvinceId = new Guid("de2567c7-c332-45e5-81a7-449d2f753a3b"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Valle del Cauca"
                        },
                        new
                        {
                            ProvinceId = new Guid("e6f24a6f-f852-4c5d-8d5e-4dc03e5a4214"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Vaupés"
                        },
                        new
                        {
                            ProvinceId = new Guid("daaff97f-5979-43f0-ae0b-8e5a7d44fa17"),
                            CountryId = new Guid("f634d003-1fd9-4981-958c-abed8d887f82"),
                            Disabled = false,
                            Name = "Vichada"
                        });
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.RoleModel", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_role_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rol_created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rol_deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rol_description");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("rol_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rol_updated_at");

                    b.HasKey("RoleId");

                    b.HasIndex("Name", "DeletedAt")
                        .IsUnique();

                    b.ToTable("tbl_role");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CityModel", b =>
                {
                    b.HasOne("Profiles.Infrastructure.Persistence.Models.ProvinceModel", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.HasOne("Profiles.Infrastructure.Persistence.Models.CountryModel", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.CountryModel", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Profiles.Infrastructure.Persistence.Models.ProvinceModel", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
