// <auto-generated />
using System;
using Analytics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Analytics.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240523042410_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Analytics.Infrastructure.Persistence.Models.LevelModel", b =>
                {
                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_level_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rol_description");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("rol_disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("LevelId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("level");

                    b.HasData(
                        new
                        {
                            LevelId = new Guid("db7c06e7-ec3c-40fa-b521-3776f6826084"),
                            CreatedAt = new DateTime(2024, 5, 23, 4, 24, 10, 780, DateTimeKind.Utc).AddTicks(3614),
                            Disabled = false,
                            Name = "Backend"
                        },
                        new
                        {
                            LevelId = new Guid("81572849-4fd1-4220-842c-a9cb0dcb62de"),
                            CreatedAt = new DateTime(2024, 5, 23, 4, 24, 10, 780, DateTimeKind.Utc).AddTicks(3622),
                            Disabled = false,
                            Name = "Frontend"
                        },
                        new
                        {
                            LevelId = new Guid("8af5f1a9-e7d2-4368-bc10-4768661f7263"),
                            CreatedAt = new DateTime(2024, 5, 23, 4, 24, 10, 780, DateTimeKind.Utc).AddTicks(3626),
                            Disabled = false,
                            Name = "Fullstack"
                        },
                        new
                        {
                            LevelId = new Guid("61cdcbbc-645a-42cf-8ec5-c32841febe32"),
                            CreatedAt = new DateTime(2024, 5, 23, 4, 24, 10, 780, DateTimeKind.Utc).AddTicks(3630),
                            Disabled = false,
                            Name = "DevOps"
                        },
                        new
                        {
                            LevelId = new Guid("0cf40f54-d68b-4072-bef1-1d30a619991e"),
                            CreatedAt = new DateTime(2024, 5, 23, 4, 24, 10, 780, DateTimeKind.Utc).AddTicks(3634),
                            Disabled = false,
                            Name = "QA"
                        },
                        new
                        {
                            LevelId = new Guid("202cfa47-189e-482d-9a63-6cad414687ef"),
                            CreatedAt = new DateTime(2024, 5, 23, 4, 24, 10, 780, DateTimeKind.Utc).AddTicks(3639),
                            Disabled = false,
                            Name = "UX/UI"
                        },
                        new
                        {
                            LevelId = new Guid("95e3b072-05b5-4f49-9352-8d1f334095e6"),
                            CreatedAt = new DateTime(2024, 5, 23, 4, 24, 10, 780, DateTimeKind.Utc).AddTicks(3643),
                            Disabled = false,
                            Name = "DataScience"
                        },
                        new
                        {
                            LevelId = new Guid("75b5cd1c-f198-46a9-a02b-6500384d4d7a"),
                            CreatedAt = new DateTime(2024, 5, 23, 4, 24, 10, 780, DateTimeKind.Utc).AddTicks(3647),
                            Disabled = false,
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            LevelId = new Guid("2625b027-05bf-4cef-b1cf-99cae799aa31"),
                            CreatedAt = new DateTime(2024, 5, 23, 4, 24, 10, 780, DateTimeKind.Utc).AddTicks(3650),
                            Disabled = false,
                            Name = "Product"
                        },
                        new
                        {
                            LevelId = new Guid("5b935487-4ef9-4641-9ff1-92785f80d578"),
                            CreatedAt = new DateTime(2024, 5, 23, 4, 24, 10, 780, DateTimeKind.Utc).AddTicks(3655),
                            Disabled = false,
                            Name = "Project"
                        },
                        new
                        {
                            LevelId = new Guid("b88ecaad-991f-4d42-84e7-c07832369328"),
                            CreatedAt = new DateTime(2024, 5, 23, 4, 24, 10, 780, DateTimeKind.Utc).AddTicks(3659),
                            Disabled = false,
                            Name = "Management"
                        },
                        new
                        {
                            LevelId = new Guid("91a14b3b-0d12-4b8d-b3f0-beee70c7c9dd"),
                            CreatedAt = new DateTime(2024, 5, 23, 4, 24, 10, 780, DateTimeKind.Utc).AddTicks(3662),
                            Disabled = false,
                            Name = "Other"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
